### ISSUE TITLE
Crafts cannot rotate using helm signs or /rotate

### ISSUE THREAD

**Issue by TDLF8** [APDevTeam/Movecraft#100]
**Describe the bug**
Crafts do not rotate

**To Reproduce**
Pilot a craft, I used an airskiff
attempt to use a [helm] sign or /rotate left or right
craft will freeze and be unable to be used in addition to not turning.

**Expected behavior**
Craft to turn left or right

 - Movecraft: [e.g. 7.0.0 prerelease 6]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [e.g. 1.12.2]

**Comment by cccm5** [comment]
Could you tell me what minecraft and movecraft versions you're using

**Comment by TDLF8** [comment]
Movecraft 7.0 pre_release 6

Minecraft Spigot 1.12.2

**Comment by TDLF8** [comment]
> Could you tell me what minecraft and movecraft versions you're using

@cccm5 I have also tried this on previous pre-releases, and the problem stays the same

**Comment by TheRealBotcrusher** [comment]
I'm unable to reproduce with spigot 1.12.2 and pre_release 6.

Is anything different than the stock movecraft configuration? Any tweaks to the airskiff craft file?

Alternatively, are you using a non-standard build of spigot?

If you've gotten any errors in your logs, it would greatly help.

**Comment by TDLF8** [comment]
> I'm unable to reproduce with spigot 1.12.2 and pre_release 6.
> 
> Is anything different than the stock movecraft configuration? Any tweaks to the airskiff craft file?
> 
> Alternatively, are you using a non-standard build of spigot?
> 
> If you've gotten any errors in your logs, it would greatly help.

@TheRealBotcrusher 

I have modified most of the default craft files, tweaking allowed blocks and flyblock percentages.
This problem doesn't appear to be specific to one kind of craft, as all crafts face the same issue. They are able to move on all axis, the issue only arises when they rotate.

As far as I know, I am using the standard version of spigot.
The following text is the server log from attempting to rotate an Airship


11.04 21:02:46 [Server] INFO Player Aero88 has released a craft of type Airship with size 1054 at coordinates : -23 x , 101 z
11.04 21:02:18 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
11.04 21:02:18 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(WorldGuardPlugin.java:993)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.protection.GlobalRegionManager.canBuild(GlobalRegionManager.java:163)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.protection.GlobalRegionManager.hasBypass(GlobalRegionManager.java:122)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:508)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:344)
11.04 21:02:18 [Server] WARN at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:219)
11.04 21:02:18 [Server] WARN java.lang.NullPointerException
11.04 21:02:18 [Server] ERROR Internal - Error - Processor thread encountered an error
11.04 21:02:13 [Server] INFO Player Aero88 piloted a craft of type Airship with size 1054 at location: -23 x, 101 z

**Comment by TDLF8** [comment]
My apologies, the issue has been fixed. Reading my own log, the error was caused by an outdated version of WorldGuard. 

All crafts are fixed. Resolved

Thank you
