### ISSUE TITLE
Idea: Multiverse Support (Crafts Between Worlds)

### ISSUE THREAD

**Issue by SirEraz** [APDevTeam/Movecraft#101]
I've seen a few servers that have a custom plugin(s) that allow their Movecraft ships to move between worlds. In particular, I'm referring to space servers. Generally, this causes crafts to teleport to a different Multiverse world, along with everyone inside the craft, when they enter a certain pre-defined region. Usually in such servers it is used to allow spaceships to travel between a space world and multiple planets.

I think that adding this feature into Movecraft would open up a whole new world of possibilities for server owners using Movecraft. I think that if this feature was to be implemented, it should allow the end teleport locations to be defined both by world and X Y Z coordinates (instead of just teleporting a craft to a world's spawn).

**Comment by cccm5** [comment]
Ya its definetley  something that I would want to do in addition to bungeecord. If it's added, it will definitely be after the next official release however.

**Comment by TrollyLoki** [comment]
Hey! I think this would be a really cool addition. I'm going to try to get it to work.

**Comment by TrollyLoki** [comment]
Hello!
I'm working on adding this feature to my fork of Movecraft

**Comment by eirikh1996** [comment]
That's cool @TrollyLoki . Are you making a pull request on it once it is working?

**Comment by TrollyLoki** [comment]
Yes, I will

**Comment by eirikh1996** [comment]
Hello @TrollyLoki . Is there still any progress on the Multiworld support?

**Comment by TrollyLoki** [comment]
@eirikh1996 Yes, I have a build with working world switching but there are still some errors to be worked out. I have listed them in the issues section of my fork

**Comment by StarWarden** [comment]
In addition to crafts being able to travel between worlds  (and servers via bungeecord), would it be possible to to travel between dimensions (nether and end) as well? You could travel between dimensions within one world and also between dimensions in different worlds.

**Comment by TrollyLoki** [comment]
The ability to travel between dimensions is what I am working on

**Comment by SirEraz** [comment]
@StarWarden if it’s using Multiverse that’d probably already be possible since MV counts those as worlds, idk how it’s being implemented rn though

**Comment by TrollyLoki** [comment]
The way I am implementing it it will be possible to travel between any worlds that bukkit has loaded, meaning the nether, the end, and any other additional worlds loaded by multiverse

**Comment by Blinkve** [comment]
Greetings, @TrollyLoki ! My apologies about the @, any news on the multiverse integration? [or if it's possible for us to use the unfinished build on our own]

**Comment by TrollyLoki** [comment]
If you know how you can build my fork of movecraft. I don't plan to release a prebuilt version until I've fixed the problems.

**Comment by TrollyLoki** [comment]
I have released a new beta build which fixes the occasional problems with teleportation.

**Comment by TrollyLoki** [comment]
I am considering adding built in nether portal support to my multiworld fork. I have more information here: TrollyLoki#12
I would appreciate any input on this idea.

**Comment by EenDev** [comment]
That is a VERY cool idea! My input is you should hook a portal to a portal in another world, so it works from world - world and not just the nether

**Comment by cccm5** [comment]
> That is a VERY cool idea! My input is you should hook a portal to a portal in another world, so it works from world - world and not just the nether

I think for something like that it'd be better to piggy back off another portal plugin with an addon
