### ISSUE TITLE
Remote sign limits

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#107]
**Problem:** Remote signs can activate an unlimited number of signs (including 100+ torpedo crafts)

**Solution:** Add a config to movecraft for the maximum number of remote signs that can be activated at once.

**Questions:** What should happen if you have more than the maximum number of signs?  Should the first portion of them be activated and then ignore the rest?  Should the remotes all fail and declare that to the pilot?

Personally, I lean toward failing and notifying the user, but I'd like to hear from @cccm5

**Comment by cccm5** [comment]
This sounds like a reasonable system. Key things would be that setting it to -1 should allow for unlimited amounts, and it should only ever notify the user once. I would also say that if any fail, they all fail. I'll leave the default setting to you.
