### ISSUE TITLE
Rmove signs do not work

### ISSUE THREAD

**Issue by TDLF8** [APDevTeam/Movecraft#109]
RelativeMove (RMOVE) (Rmove) signs do not work. No error message, they do nothing.

**Comment by TylerS1066** [comment]
What versions of minecraft, bukkit/spigot/paper, movecraft, and other plugins are you using?

**Comment by cccm5** [comment]
I've tested this in game and validated that it works. Make sure you have your crafts configured correctly - there are settings related to static movement that effect `RMove` signs.
