### ISSUE TITLE
Add more internationlization suppourt

### ISSUE THREAD

**Issue by cccm5** [APDevTeam/Movecraft#111]
**Is your feature request related to a problem? Please describe.**
Many new additions to the code-base do not properly use the internationalization system implemented in the plugin.

**Describe the solution you'd like**
Any output that is sent to players, such as command feedback, cruise status, and possibly sign headers, should be processed through the `I18nSupport` class. Defaults should also be added to the language files.

**Comment by drfiveminusmint** [comment]
currently trying to go through the files and get these cleaned up
