### ISSUE TITLE
Config option to change wool and redstone percentages required?

### ISSUE THREAD

**Issue by ZSky312** [APDevTeam/Movecraft#112]
Hello, I couldn't find an option to change the wool and redstone blocks required in the configs. I really don't like building out of wool so I looked for options to make it so that I don't require any, or just a few blocks to build the crafts from, but I couldn't find any config in the files that would change this. Is there an option, or has there one not been added yet?

**Comment by cccm5** [comment]
Hi,
Check [this](https://github.com/APDevTeam/Movecraft/wiki/Type-File) wiki page for details what each craft type does. You should just need to change `flyblocks` and `allowedBlocks`
