### ISSUE TITLE
Air pockets form behind a cruising watercraft with space below the waterline

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#115]
**Describe the bug**
When you make a watercraft and make hollow spaces in it below the waterline, then cruise it, it leaves a trail of air pockets behind it

**To Reproduce**

1. Pilot any watercraft that has an open/hollow space extending below the waterline (I used a Ship craft type).
2. Make it cruise, and watch the trail of air pockets forming behind it.

**Expected behavior**
When cruising a watercraft, water is supposed to form behind.

**Screenshots**
![2019-06-27_17 33 05](https://user-images.githubusercontent.com/11066794/60279780-fcfd8180-9901-11e9-9647-f8a5a5b84f17.png)
![2019-06-27_17 33 16](https://user-images.githubusercontent.com/11066794/60279783-fcfd8180-9901-11e9-8034-3ea59801bf3f.png)
![2019-06-27_17 33 19](https://user-images.githubusercontent.com/11066794/60279784-fcfd8180-9901-11e9-9428-4c4cd8d2a124.png)
![2019-06-27_17 33 20](https://user-images.githubusercontent.com/11066794/60279785-fd961800-9901-11e9-823d-bfe34d792404.png)

**Versions (please complete the following information):**
 - Movecraft: 7.0.0 prerelease 8
 - Java JDK 8.0.1
 - Minecraft 1.10.2

**Additional context**

**Comment by cccm5** [comment]
Very strange that the air pockets are forming outside of the boundaries (the furthest extends of the craft in each direction) of the craft itself, those should automatically be handled by the algorithm.

**Comment by galacticwarrior9** [comment]
Still present in latest pre-release and in the latest build of eirikh's fork. The effect it can have on worlds can be devastating. Take a look at our [server map](http://map.ccnet.gq/)  - the streaks in the oceans are all air pockets caused by this bug.
