### ISSUE TITLE
Request: /cruise in the direction you are facing.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#12]
using /cruise should work with the direction you are facing, N/E/S/W and everything in between like North East without needing to supply a sub-command, it should work based on whatever direction you are facing. It should also act as a toggle, so /cruise starts cruising, and it also stops if you are already cruising for simplicity.

**Comment by cccm5** [comment]
[This is definitely going to be a thing](https://github.com/APDevTeam/Movecraft/blob/master/modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/CruiseCommand.java#L27), but I wanted to get a semi-stable pre-release out quickly and forgot about it. Should be added sometime soon.

**Comment by MrUniverseAP** [comment]
Hallo, on le todo and getting done!

**Comment by FrozenBeard** [comment]
@MrUniverseAP Sweet thanks bro!

**Comment by cccm5** [comment]
Added!
