### ISSUE TITLE
Request: Admin tools / Better user feedback

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#13]
One issue I have had from time to time, is when movecraft breaks, it breaks in fashion. The recent issue I have with my build (an ancient build) is that somehow double chests manage to somehow start working and movecraft throws a billion errors a second brining the TPS of the server to a grinding hault and finally killing the server. I have no idea how the hell some players manage the cause the ship to sometimes get double chests working/moving, but its happened a few times and it crashes the server completely.

**Request Admin Tools.**

- List all active running ships, with their players, shiptype, location, all with JSON clickable events in chat, so I can click on the coordinates of the ship and it'll teleport me to that current ship/player.
- Stop all ships in case of emergency, as described above.
- Stop/Freeze a specific ship easily, this could be a clickable event from the List of all active ships.
- Sink a ship on command (I see you're going to add this!)

**Better user feedback**
I've run movecraft since the dawn of time, my servers 5 years old, I've run movecraft for 4.
The biggest and hardest thing for new players to understand is how to build a ship, as there isn't much feedback when there creating a ship, it could simply be when they right click the ship name sign, it tells them the requirements, size limits, ship specs like speed etc, and how far away they are from these things. Some extremely basic feedback would go a long way. in a nicely formatted text box, not just white text!
I re-wrote all my messages to have color and prefixes so its better seen in chat, but im limited without extra information being delivered!

**Comment by cccm5** [comment]
So for the first one, their's /craftreport which has all that, just without the clickable chat entries. I'll see what I can do for adding those, as it seems very useful. for stopping all ships or ships of a player, you can do /release <playername> to release a player or /release -a.

Better user feedback is another thing I want to do, but I want to make sure I do it right. I do plan on reformatting most of Movecraft's text output (which you can see in /contacts and /craftreport), so it will probably happen when I start doing that.

**Comment by FrozenBeard** [comment]
Maybe instead of having a bunch of really random commands its all tied together.
/craftreport (Would be better as /craftlist or /craftslist) I can never remember craftreport, ill have to alias it.
```
1. Username | Dhow | 323 Blocks | -20, 63, 100 | [Stop Craft]
2. Username | Dhow | 372 Blocks | -20, 63, 120 | [Stop Craft]
3. Username | Dhow | 383 Blocks | -20, 63, 130 | [Stop Craft]
4. Username | Dhow | 329 Blocks | -20, 63, 140 | [Stop Craft]
                                                                            [Stop All Crafts]
<< Previous | Next >>
```
Formatting idea.
Clicking username or the TPPOS could teleport you to them, clicking the stop craft would stop it, clicking the scroll arrows scrolls through the pages of crafts piloted. Stop all crafts, would need a conformation to make sure you dont accedently  click it.

Alternative, **Show it in a GUI!** use the minecraft boat icon to display each piloted craft in the GUI, when you hover over it, it gives you information, when you click it it teleports you to that player thats piloted it! Then you could even have an item next to each to stop it, or an item bottom right of the GUI to stop all.

**Comment by cccm5** [comment]
Ok, I'm going to close this now that all the non duplicate items have been implemented
