### ISSUE TITLE
Craft disappears on rotate

### ISSUE THREAD

**Issue by hmmcrunchy** [APDevTeam/Movecraft#15]
when rotating either via helm sign or command craft disappears completely then registers as taking too much damage and sinking

no error messages

**Comment by cccm5** [comment]
Can you send me the craft file (I assume you're on 1.12)

**Comment by hmmcrunchy** [comment]
hi there 

yes 1.12.1 

https://pastebin.com/rrVXqLjc

**Comment by galacticwarrior9** [comment]
Also have the same problem.

**Comment by cccm5** [comment]
Fixed in https://github.com/APDevTeam/Movecraft/commit/1381af1a73ce65d4c4cf5116d4613d0d45b55a34
