### ISSUE TITLE
Hitbox doesn't include the top block of a craft

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#154]
**Describe the bug**
Using the locationInHitBox util returns false when the player is standing on a block that is one below the top of a craft or higher.

Currently, #143 uses locationNearHitBox to bypass this but we should attempt to fix the hitbox.

**Comment by cccm5** [comment]
You should use `locIsNearCraftFast` instead - `locationInHitBox` is for queries specific to the bounds of the HitBox.
