### ISSUE TITLE
Auto-fill signs on pilot

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#155]
**Is your feature request related to a problem? Please describe.**
It would be awesome if you could format signs in a specific way such that they automatically get filled out when the craft is piloted.

**Describe the solution you'd like**
Ideally, it would depend on the exact implementation, but onCraftDetect, signs of the specific form get filled out.

Examples:
```
Place crew:
sign here
<blank>
<blank>
```
to
```
Crew:
[Pilot's IGN]
<blank>
<blank>
```

```
Place pilot:
sign here
<blank>
<blank>
```
to
```
Pilot:
[Pilot's IGN]
<blank>
<blank>
```

And possibly some sort of config for [Private] and more signs, but I suspect this will be best for a separate plugin (but I wanted to get the idea written down).

**Comment by FrozenBeard** [comment]
I requested this back in ~2016 time, Would like to see this too.

**Comment by HumorousFool** [comment]
I shall look into this when I stop procrastinating.

**Comment by TylerS1066** [comment]
This would be a relatively simple addon to code, just listen for CraftPilotEvent and fill the signs.

**Comment by HumorousFool** [comment]
This is very interesting, I'll be starting an addon soon

**Comment by HumorousFool** [comment]
This has been implemented in Movecraft-AutoSign and can be closed.
