### ISSUE TITLE
Feature Request: Use SimpleClans intergration for Crew ships

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#156]
**Is your feature request related to a problem? Please describe.**
Instead of having to set each users name on a sign as part of your Crew on a ship, for re-spawns, for attacking land etc, use an existing Crew management plugin, I have used SimpleClans for years and its perfect with the amount of features it packs in, its even got an API.
https://github.com/marcelo-mason/SimpleClans

**Describe the solution you'd like**
When a user builds a ship, they do **/setship** which auto sets that as a Crew ship once piloted (like sethome as it will have the manoverboard warp), everyone in the SimpleClans crew thats on the ship will then have a manoverboard area from one Crew Sign that is placed (No longer needing to have one for every single person) and a unified spawn location. 

This opens up a metric ton of additional features for later:

1. The system to attack land would allow just setting the crew permission to the region to allow the entire crew to use it, even if they wasn't part of the attack.
2. Simpleclans has a  Alliances & Rivalries system, and a way to start a war (That does nothing at present, but theres an API to make something happen when they go to war)
Once in war, this could then record ship battle stats into a database, how many ship vs ship battles, who won the fight, to then build points for each crew to have ship battles as there would be an incentive to get a higher score.
3. Once a ships piloted and set as a crew ship, there could be a **/shipsnear** (like /near) to detect Alli or Rival ships nearby.
4. You could put a hologram of the crews name above the ship when it sails to show its piloted by a crew, with their Crew name/Amount of people on deck.

I request this back in #14 but this is a more precise list of features and how to implement.

**Comment by cccm5** [comment]
Please update #14 instead of creating a new issue
