### ISSUE TITLE
Add passable and destruction blocks

### ISSUE THREAD

**Issue by cccm5** [APDevTeam/Movecraft#17]
Passable Blocks:
At the moment, a craft can configured in a way to pass through water and act like a boat. The goal of this new system is to extend this functionality to any and all blocks. If a block type is added to the passable list, it will be "phased through" by a craft. If a craft is released while in this state it will either delete the blocks or it will be unable to be released (Haven't decided yet).
Destruction blocks:
These are like harvest blocks, but don't get... harvested. These blocks are destroyed by ships as they pass through them

**Comment by FrozenBeard** [comment]
Was the turning in water issue solved?

**Comment by cccm5** [comment]
ya i just have to fix another issue with sub-craft turning
