### ISSUE TITLE
Sinking crafts with water in its hitbox leaves water pillars

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#174]
**Describe the bug**
Crafts that has water as part of their hitboxes (for example as ballistic fluid in their guns or as part of bath tubs in quarters) will leave pillars of water when they sink.

**To Reproduce**
1. Pilot a craft that's type has water as an allowed block (I used a Silver Empire lightcruiser, which is an Airship type)
2. Pilot the craft
3. Cause it to sink, either through taking damage or by /scuttle
4. Watch as pillars of water form from the water locations on the craft

**Expected behavior**
No water pillar should form when a craft with water on it sinks

**Screenshots**
![2019-10-06_01 39 34](https://user-images.githubusercontent.com/11066794/66262128-ee651700-e7da-11e9-8db3-ead75b9e386e.png)
![2019-10-06_01 40 26](https://user-images.githubusercontent.com/11066794/66262129-ee651700-e7da-11e9-9c17-3f29e06bc6c7.png)
![2019-10-06_01 40 29](https://user-images.githubusercontent.com/11066794/66262130-ee651700-e7da-11e9-9b06-c9ff523e338b.png)

**Versions (please complete the following information):**
 - Movecraft: 7.0.0_release_candidate_1
 - Java JDK 8
 - Minecraft 1.11.2

**Additional context**

**Comment by cccm5** [comment]
It appears that this has been fixed by 6883774
