### ISSUE TITLE
Has harvestBlocks been implemeted yet, or am I doing it wrong?

### ISSUE THREAD

**Issue by themindstorm** [APDevTeam/Movecraft#178]
This is from the wiki. I tried adding strings of blocks to harvest, but I think I have made a mistake.

It says "strings, not integers", so I put the name in full.
```
# Not Required.
# If set, hover type crafts will allow the vehicle to move through the listed blocks. 
# Blocks must be strings, not integers, similar to the following: http:jd.bukkit.org/rb/apidocs/org/bukkit/Material.html 
# Typically this would be set to grass or flowers so your ground vehicles are not obstructed by them.
harvestBlocks: 
  - "GRASS"
  - "TALL_GRASS"
  - ...
```

The craft still won't harvest grass, so what am I doing incorrect?

**Comment by eirikh1996** [comment]
did you add harvesterBladeBlocks too?

**Comment by eirikh1996** [comment]
@themindstorm

**Comment by eirikh1996** [comment]
No. harvesterBladeBlocks are the blocks that have the same functions as a harvester blade

**Comment by themindstorm** [comment]
Can you show me exactly how to use harvestorBladeBlocks? I couldn't find any documentation. This is what I have right now:

```
harvestBlocks: 
  - "LONG_GRASS"
  - "GRASS"

harvesterBladeBlocks: 
  - "LONG_GRASS"
  - "GRASS"
```

**Comment by cccm5** [comment]
You can use the same format you use for specifying `allowedBlocks`. For a list of crafttype configs, look here https://github.com/APDevTeam/Movecraft/wiki/Type-File.

**Comment by cccm5** [comment]
I'm assuming that you're all set now so I'm gonna go ahead and close this
