### ISSUE TITLE
Container GUIs close when ship moves

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#182]
**Describe the bug**
When changing the contents of inventory blocks, such as dispensers, chests, etc..., the GUI for the container closes when the ship moves. 

**To Reproduce**
1. Pilot a ship with containers on it
2. Cruise the craft
3. While cruising, open one of the containers and keep it open
4. See how the GUI closes when the craft moves

**Expected behavior**
Players should be able to edit container contents while craft is in motion.

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 beta 1]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [1.11.2, 1.12.2]

**Additional context**

**Comment by FrozenBeard** [comment]
I was going to report this and forgot to! Good job
