### ISSUE TITLE
Ground vehicles cannot move over grass despite using phaseable and harvestable block options

### ISSUE THREAD

**Issue by jamesol1** [APDevTeam/Movecraft#183]
**Describe the bug**
I've made a ground vehicle and have noticed that despite having grass/tall grass in both harvestable blocks (under iron blocks which is what the ship is moving along the floor with in the video) AND phaseable blocks... i still get this issue where if a vehicle is moving on top of 'grass' it produces an error saying ''your craft cannot move over long grass". The video below shows it. I've also got grass blocks as being harvestable just a added note.
https://youtu.be/cRrAy3tM6XM

**To Reproduce**
Replicate what i had in the video. Make it so that your vehicle is in a position to move over grass, not through it. 
https://pastebin.com/5UiHezMP
^ that is my craft file type. As you can see i have setup both harvestable blocks with a blade and phaseable blocks. 

**Expected behavior**
You should get ''your craft cannot move over long grass"... with your vehicle unable to move in the direction your moving, perhaps multiple directions... it depends.

**Versions (please complete the following information):**
 - Movecraft: Movecraft 7.0.0 Beta 1 
 - Minecraft 1.12.2

**Comment by cccm5** [comment]
This is probably going to be resolved when we figure out the best method for #179
