### ISSUE TITLE
Higher scaling of terrain for ground vehicles setting

### ISSUE THREAD

**Issue by jamesol1** [APDevTeam/Movecraft#187]
**Feature request**
With ground vehicles any terrain higher than 1 block stops your vehicle. I'd love for vehicles to have the potential to scale terrain better so that they can be used on the survival map as opposed to just being for flat roads. The ground vehicles im planning on having are also quite large so 1 block scaling doesnt match their sheer size.

**Solution**
Make it so ground vehicles can climb/scale terrain higher than 1 block by a configurable amount. I know you can sort of achieve this through adding hover but of course making tanks for instance hovering looks naff. 

Thanks!

**Comment by wolfebersahd** [comment]
This was controlled by HoverHeight or whatever the feature was in previous versions.

A HoverHeight of 1 allows it to scale up one block, a HoverHeight of 2, allowed it to scale two block then readjust it's height according to the new terrain.

At least that's how it worked in older versions of Movecraft.

**Comment by jamesol1** [comment]
This doesn't seem to work for me.

**Comment by cccm5** [comment]
This should be fixed. You can configure incline heights via the `gravityInclineDistance` flag
