### ISSUE TITLE
API

### ISSUE THREAD

**Issue by hmmcrunchy** [APDevTeam/Movecraft#19]
HI There 

working great and a lot faster now :) 

just wondering whether any of the API will be put back in. things like 

utils.MovecraftLocation; which I used for iterating through the ships blocks quickly is returned by craft.getBlockList

I see Craft has been changed to ICraft but the CraftManager.getInstance().getCraftsInWorld(world); still returns Craft not ICraft 

really great work though looking forward to trying this on my main server

**Comment by cccm5** [comment]
Nothing was removed, things were just moved around to facilitate the update. I recommend viewing the file structure of the compiled jar for the package layout until I compile the javadocs.

**Comment by hmmcrunchy** [comment]
Ha cool thanks I’ll try and find stuff :)

**Comment by eirikh1996** [comment]
So you are making javadocs too @cccm5 ?

**Comment by cccm5** [comment]
Yes, but not until the release is stable.
