### ISSUE TITLE
Water vaporization

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#193]
**Describe the solution you'd like**
Rather than water protecting all nearby blocks from exploding, make it so that when a block near water explodes it will cause the water, and any water connected to it, to vaporize.

Also please avoid letting cannons blow up after the first shot.

**Comment by TylerS1066** [comment]
Additionally, it would be nice to add the ability to vaporize all "liquids" to avoid lava spills.

**Comment by FrozenBeard** [comment]
Not good for water based ships.

**Comment by TylerS1066** [comment]
> Not good for water based ships.

Good catch, maybe this should be configurable for the amount of water it can vaporize?  If the vaporized block size is greater than the config it stays how spill protection works, otherwise it vaporizes?

The alternative is to config it on a per craft basis, but that seems excessive to me.  Or maybe limit it to only liquids on the craft?

**Comment by cccm5** [comment]
This will only be looking for water flow events that initiate from inside of a craft. Water craft won't have issues.
