### ISSUE TITLE
Small ground vehicles work, large ones do not?

### ISSUE THREAD

**Issue by Skyior** [APDevTeam/Movecraft#200]
**Describe the bug**
I am trying to create tanks on my server. I was concerned about whether the older version supported ground vehicles or not and was pleasantly surprised when I got a little 10 block motorcycle to work. Then I went to go build a larger 500 block vehicle for the land, and it will move, but not climb up anything despite having only a single block to climb over. I made a little 100 block one, and that worked however. I'm not certain what the issue is, but the have two distinct error messages.

**To Reproduce**
1. build a small vehicle.
2. try to move directly up with the wand
3. build large vehicle
4. try to move directly up with the wand
5. be sure to use the same type of vehicle

**Expected behavior**
When moving directly up with the smaller vehicle, I get something along the lines of "reached height limit!"
However when I try with the large one, It says "cannot move, path was obstructed." But there is literally nothing above it. In fact it always names the block touching it on the bottom.

**Screenshots**
![Screenshot (28)](https://user-images.githubusercontent.com/52142131/69926332-b1836c80-1479-11ea-97e4-860306bc7821.png)

![Screenshot (32)](https://user-images.githubusercontent.com/52142131/69926540-7afa2180-147a-11ea-8b06-7bb86473ef6f.png)
![Screenshot (31)](https://user-images.githubusercontent.com/52142131/69926546-7fbed580-147a-11ea-950f-f9a015b11ef3.png)
![Screenshot (30)](https://user-images.githubusercontent.com/52142131/69926555-83525c80-147a-11ea-93ce-476f47740bae.png)
![Screenshot (29)](https://user-images.githubusercontent.com/52142131/69926559-864d4d00-147a-11ea-9e72-b6a75069eefe.png)

**Versions**
 - Movecraft: v3.1.X80
 - Minecraft 1.7.10

**Additional context**
I was trying to use the Hovering feature, but it seems to not be working, I thought it would fix the issue perhaps.

**Comment by eirikh1996** [comment]
hoverHeight currently has no functionality at the moment

**Comment by Skyior** [comment]
Then what should I do to fix this. Just remove canHover and hoverHeight? I believe I tried that, but I'll double check

**Comment by Skyior** [comment]
I got it working. Thank you!
