### ISSUE TITLE
Tall grass turns into a deadbush when being unphased

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#203]
**Describe the bug**
When moving a craft with LONG_GRASS as part of passthroughBlocks over grass, the grass is being phased. However, when the same block is being unphased, it turns into a deadbush instead of long grass

**To Reproduce**
1. Pilot a craft type having "LONG_GRASS" added to the passthroughBlocks list flag
2. Move it across a field of long grass
3. Watch the trail of deadbushes appearing behind

**Expected behavior**
Grass being phased should be unphased as grass

**Screenshots**
![2019-12-03_19 44 09](https://user-images.githubusercontent.com/11066794/70079880-ddcbf400-1605-11ea-836a-dc6c69bc6b34.png)
![2019-12-03_19 47 34](https://user-images.githubusercontent.com/11066794/70079882-ddcbf400-1605-11ea-8983-d3b9c8386955.png)
![2019-12-03_19 47 51](https://user-images.githubusercontent.com/11066794/70079883-de648a80-1605-11ea-95a3-cee7ec754cef.png)

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 beta 1]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [e.g. 1.12.2]

**Comment by cccm5** [comment]
Phasing should probably be changed to store data in addition to id's.

**Comment by eirikh1996** [comment]
> Phasing should probably be changed to store data in addition to id's.

I agree to that. This can easily be abused to get free deadbushes
