### ISSUE TITLE
Slow cruise/cruise2

### ISSUE THREAD

**Issue by jamesol1** [APDevTeam/Movecraft#204]
Given the much improved ability to move around on ships when cruising i was wondering if you could add a second cruise setting that people could activate. Therefore i for instance would have it so one is for fast travelling... the other is for slowly getting to a location while going around my ship/vehicle sorting chests/doing stuff etc or just surveying in an area.

For the project i have in mind this would be really good as i plan to have more then just cannons/chests on my vehicles.

So you'd have two different modes...
Cruise: OFF
Cruise2/SlowCruise: OFF

EDIT: If there was a way of making it so the fuel burn rate could be different when using cruise2/slow  cruise that would be amazing.

**Comment by cccm5** [comment]
Something akin to a throttle has been frequently requested, but it's unclear to me if there's a good way to implement it. I personally don't like limiting it to a second locked in "slow cruise", however I think a sign where you left/right click to increase/decrease throttle would be a good idea.

**Comment by jamesol1** [comment]
Yeah i agree restricting it to be a slow cruise mode would not benefit as many people. I'd suggest have a second cruise sign 'Cruise2' of which players can give different speed settings to compared to the default cruise. That throttle idea sounds even better though, whether it would be harder to add im not sure.

**Comment by TylerS1066** [comment]
This would be solved with a correct implementation of #335 .

**Comment by TylerS1066** [comment]
With #335 merged, this is solved!
