### ISSUE TITLE
Gravity not working? Minecraft 1.8.8

### ISSUE THREAD

**Issue by Skyior** [APDevTeam/Movecraft#209]
**Describe the bug**
Vehicles that use gravity instantly start to sink upon going down a ledge

**To Reproduce**
configure and build a ground vehicle that uses the gravity flag

**Expected behavior**
It should sink and stop functioning upon leaving a ledge

**Versions:**
 - Movecraft: 4.0.1
 - Minecraft 1.8.8

Is there a problem with the gravity flag in this version? I updated from 1.7.10

**Comment by cccm5** [comment]
I unfortunately have no idea how Movecraft 4 functioned, I've only been working with the code-base since somewhere around version 5.
