### ISSUE TITLE
Not working on 1.11.2

### ISSUE THREAD

**Issue by keough99** [APDevTeam/Movecraft#21]
I'm having an issue where the plugin isn't working and you can't pilot any crafts on 1.11.2 but there's no errors in console. I am using the latest release that was released on the github releases page on this repository

**Comment by cccm5** [comment]
can you post your startup log

**Comment by keough99** [comment]
https://cdn.discordapp.com/attachments/228630467748823040/368919352767938560/latest_2.log

**Comment by cccm5** [comment]
Download movecraft again, you're on an outdated version. There are several errors in your log

**Comment by cccm5** [comment]
Any news?

**Comment by keough99** [comment]
I'll download movecraft again today I haven't had much time lately to download and upload the jar to my server yet

**Comment by keough99** [comment]
i downloaded and reuploaded the jar and restarted the server and still having issues
[latest (3).log](https://github.com/APDevTeam/Movecraft/files/1405396/latest.3.log)

**Comment by keough99** [comment]
Any news on this issue, has anyone else ran into this issue and found a solution?

**Comment by cccm5** [comment]
I know the issue I just am waiting until friday/the weekend for when I have time to fix it

**Comment by keough99** [comment]
Ok

**Comment by keough99** [comment]
fixed the issue my sieges.yml was the issue
