### ISSUE TITLE
LICENSE include wrong?

### ISSUE THREAD

**Issue by Buh13246** [APDevTeam/Movecraft#211]
the LICENSE is not included in the jar.

possible Reason: File /modules/Movecraft/pom.xml Line 146.
`                <includes>
                    <include>LICENSE</include>
                </includes>`

after changing to LICENSE.md the license is included.

git diff modules/Movecraft/pom.xml

```
--- a/modules/Movecraft/pom.xml
+++ b/modules/Movecraft/pom.xml
@@ -143,7 +143,7 @@
                 <targetPath>.</targetPath>
                 <directory>../../</directory>
                 <includes>
-                    <include>LICENSE</include>
+                    <include>LICENSE.md</include>
                 </includes>
             </resource>
         </resources>
```
is this intended or just a typo?

Thx for reading.

**Comment by cccm5** [comment]
Wups, that definitely a bug

**Comment by Buh13246** [comment]
I will fix it and make a pull request.
