### ISSUE TITLE
IDS not working on 1.15.1

### ISSUE THREAD

**Issue by rodrigosky** [APDevTeam/Movecraft#215]
im trying to add some ids for the ship craft like "FURNACE" or " SPRUCE_TRAPDOORS" and they dont workd

**Comment by rodrigosky** [comment]
SPRUCE TRAPDOOR*

**Comment by rodrigosky** [comment]
name: Ship
maxSize: 5000
minSize: 100
allowedBlocks:
        - LAVA
        - OAK_PLANKS
        - SPRUCE_PLANKS
        - BIRCH_PLANKS
        - JUNGLE_PLANKS
        - ACACIA_PLANKS
        - DARK_OAK_PLANKS
        - OAK_STAIRS
        - SPRUCE_STAIRS
        - BIRCH_STAIRS
        - JUNGLE_STAIRS
        - ACACIA_STAIRS
        - DARK_OAK_STAIRS
        - OAK_SLAB
        - SPRUCE_SLAB
        - BIRCH_SLAB
        - JUNGLE_SLAB
        - ACACIA_SLAB
        - DARK_OAK_SLAB
        - ALL_LOG
        - all_planks
        - GLASS
        - LAPIS_BLOCK
        - DISPENSER
        - NOTE_BLOCK
        - ALL_BED
        - sticky_piston
        - piston_head
        - all_wool
        - GOLD_BLOCK
        - IRON_BLOCK
        - all_slab
        - BOOKSHELF
        - TORCH
        - FIRE
        - oak_stairs
        - birch_stairs
        - jungle_stairs
        - spruce_stairs
        - stone_brick_stairs
        - quartz_stairs
        - nether_brick_stairs
        - chest
        - redstone_wire
        - diamond_block
        - nether_brick_stairs
        - FURNACE
        - all_sign
        - ladder
        - all_door
        - lever
        - all_pressure_plate
        - redstone_torch
        - redstone_wall_torch
        - all_button
        - clay
        - all_fence
        - netherrack
        - glowstone
        - cake
        - repeater
        - all_stained_glass
        - all_trapdoor
        - all_stone_bricks
        - iron_bars
        - glass_pane
        - all_fence_gate
        - nether_bricks
        - enchanting_table
        - brewing_stand
        - cauldron
        - end_stone
        - dragon_egg
        - redstone_lamp
        - ender_chest
        - TRIPWIRE_HOOK
        - EMERALD_BLOCK
        - BEACON
        - cobblestone_wall
        - mossy_cobblestone_wall
        - FLOWER_POT
        - all_SKULL
        - all_ANVIL
        - TRAPPED_CHEST
        - COMPARATOR
        - daylight_detector
        - REDSTONE_BLOCK
        - HOPPER
        - all_QUARTZ_BLOCK
        - all_rail
        - DROPPER
        - ALL_TERRACOTTA
        - ALL_STAINED_GLASS_PANE
        - SLIME_BLOCK
        - ALL_CARPET
        - COAL_BLOCK
        - END_STONE_BRICKS
        - BARREL
        - LANTERN
        - CAMPFIRE
        - BELL
        - STONECUTTER
        - SMITHING_TABLE
        - GRINDSTONE
        - FLETCHING_TABLE
        - BEEHIVE
        - HONEY_BLOCK
        - SMOKER
        - BLAST_FURNACE
        - LOOM
        - CARTOGRAPHY_TABLE
        - SCAFFOLDING
        - ALL_BANNER
        - BANNER
        - CRAFTING_TABLE
        - WALL_TORCH
        - WALL_SIGN
        - FURNACE
        - SPRUCE_TRAPDOOR
        - OAK_TRAPDOOR
        - BIRCH_TRAPDOOR
        - ACACIA_TRAPDOOR
        - JUNGLE_TRAPDOOR
        - DARK_OAK_TRAPDOOR
        - all_banner
        - ALL_banner
        - ALL_FURNACE

**Comment by Buh13246** [comment]
I think Uppercase is only for special groups of items. Try changing SPRUCE_TRAPDOOR to spruce_trapdoor (minecraft_id) 

Item ID | minecraft:spruce_trapdoor (https://minecraftitemids.com/item/spruce-trapdoor)

It did work for me on 1.15.1

**Comment by Buh13246** [comment]
With SPRUCE_TRAPDOOR i got a Malformed craft file error
```
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
```

**Comment by eirikh1996** [comment]
Try to convert all IDs to lowercase. This has usually helped for me

**Comment by mwkaicz** [comment]
Problem isn't upper case, SPRUCE_TRAPDOOR should work.

CraftType files started to be more crazy with these long lists of blocks based on string-IDs. 
I decided to do something with it ... make them more user-friendly.
