### ISSUE TITLE
A craft with useGravity can bypass minHeightLimite.

### ISSUE THREAD

**Issue by wolfebersahd** [APDevTeam/Movecraft#216]
**Describe the bug**
A craft with useGravity can bypass minHeightLimite.

**To Reproduce**
1. Crate a craft with useGravity and a minHeightLlimit of Y=61
2. Build the craft above Y=61
3. Pilot craft
4. Stick pilot, WASD pilot, or cruise ship

**Results:**
Ship will begin falling due to gravity and sink beyond the minHeightLimit. This is more noticeable with a high cruiseSkipBlocks as it will descend multiple block per skip.

**Expected behavior**
Ship stops falling when it hits the minHeightLimit.

**Screenshots**
I can create a video/gif if needed.

**Versions (please complete the following information):**
 - Movecraft: Latest Spigot release (Movecraft 7.0.0 Beta 1 (Hotfix))
 - Java: Latest Java 8 (8 Update 231)
 - Minecraft: Paper 1.12.2

**Additional context**
This can be useful for hybrid ships that descend in air but "float" on water and don't sink too deep into it.

**Comment by TylerS1066** [comment]
@eirikh1996 ?

**Comment by TylerS1066** [comment]
@eirikh1996 any update on this?

**Comment by wolfebersahd** [comment]
I will test on the latest released build of both APDev's 1.12 version and Eirikh's 1.13+ version later today to see if it still occurs on the latest builds respectively.

I'm sorry i didn't get you message in August, I didn't get notifications for it, and i didn't think to check until now without any notifications.

**Comment by TylerS1066** [comment]
If none of those versions fixed the problem, please try this dev build: https://github.com/APDevTeam/Movecraft/actions/runs/1374233438

**Comment by TylerS1066** [comment]
Any updates on this or #444 being fixed by that dev build?  I'd like to merge the changes if it is functional.
