### ISSUE TITLE
Collision explosin and crash explosion 

### ISSUE THREAD

**Issue by hmmcrunchy** [APDevTeam/Movecraft#22]
Hey :)

I cant seem to get collision explosion to work - the craft just collides and merges. 
is it possible to explode on crash or just block movement not distort the craft on impact as it merges with other blocks 

crashing crafts just fall and stop when they hit a solid object then stay there rather than exploding on impact 

thanks for ongoing efforts with this :) love for you to see what we are trying to do :D

**Comment by hmmcrunchy** [comment]
thanks cccm  legend :) 

do I down load it from here https://github.com/APDevTeam/Movecraft/releases

**Comment by cccm5** [comment]
Not yet, I haven't published a fixed build yet but it will be there when I do.

**Comment by hmmcrunchy** [comment]
perfect thank you again. much appreciated!
