### ISSUE TITLE
Watercrafts place water in cuboid areas around a craft

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#226]
**Describe the bug**
After piloting a watercraft in a body of water, it will replace non-water blocks not part of the watercraft and below the waterline in a cuboid area around the craft with water

**To Reproduce**
1. Create a watercraft in proximity of underwater terrain, around a river bend, etc...
2. Pilot it
3. Move it with your pilot tool
4. Notice that non-water blocks are cleared around the craft.

**Expected behavior**
Blocks should not clear around that cuboid area as described above

**Screenshots**
![2020-02-26_19 02 11](https://user-images.githubusercontent.com/11066794/75373460-a601df00-58ca-11ea-8869-a9b373e27c68.png)
![2020-02-26_19 02 48](https://user-images.githubusercontent.com/11066794/75373464-a7cba280-58ca-11ea-9f82-47f322cdc4fc.png)

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 latest code]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [e.g. 1.12.2]

**Additional context**
The problem is only present at the initial movement after the craft is detected

**Comment by wolfebersahd** [comment]
OH,

So this was why a portion of my dock was missing that one time. I though I had just made a copy/paste error and thought nothing of it.
