### ISSUE TITLE
Torp explosion sizing

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#232]
**Describe the bug**
Torpedo explosion sizing is off from what 6.0 had, and I'm unsure as to why/how (awaiting details from AP players).

**Comment by eirikh1996** [comment]
Pretty sure it is due to that it had a larger explosion underwater in 5.0 and 6.0. In addition, explosions didn't depend on torpedo size as far as I know.

**Comment by TylerS1066** [comment]
> Pretty sure it is due to that it had a larger explosion underwater in 5.0 and 6.0. In addition, explosions didn't depend on torpedo size as far as I know.

This bug also affects above water, here is a comparison of 6.0 to 7.0's affect on stone (same server, same configs, same everything but movecraft):

![2020-03-22_08 34 49](https://user-images.githubusercontent.com/7319776/77251082-3d342b00-6c1a-11ea-8953-a9ffa03b29a4.png)
![2020-03-22_08 34 59](https://user-images.githubusercontent.com/7319776/77251083-3efdee80-6c1a-11ea-97c9-15b4a1b430ec.png)


Since originally reporting this, it appears that the affect (thanks to #239) has switched and now 7.0 is the correct one and 6.0 is far too large, I'll be confirming on another server shortly.

And for fun, here is the affect on airship armoring:
![2020-03-22_08 48 05](https://user-images.githubusercontent.com/7319776/77251097-5fc64400-6c1a-11ea-91d5-b4ad84a44405.png)

**Comment by TylerS1066** [comment]
I've confirmed the 6.0 test results with Airship Pirates Survival, so it appears that some change in 7.0 is reducing the explosion power of torpedoes.  Not currently sure if this is a bug or a bug fix...
