### ISSUE TITLE
explodeOnCrash

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#242]
**Describe the bug**
explodeOnCrash currently does not work.

**Comment by eirikh1996** [comment]
What was the function of explodeOnCrash? Was it that a sinking craft would explode when it hit the ground?

**Comment by TylerS1066** [comment]
> Was it that a sinking craft would explode when it hit the ground?

Yes

**Comment by TylerS1066** [comment]
I can no longer reproduce this bug, but I will do final testing tonight.

**Comment by TylerS1066** [comment]
I have confirmed that this is no longer an issue, I believe #239 inadvertently fixed this.
