### ISSUE TITLE
Crafts sometimes disintegrate or leave behind chunks of blocks after restart

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#252]
**Describe the bug**
After piloting and moving a craft to a different location on the map and then restart the server, the crafts that have been moved either appear to have disintegrated along chunk borders or have left behind chunks of blocks at the previous locations

**To Reproduce**
1. Pilot a craft
2. Move the craft to another location in the world
3. Released or not, stop and reboot the server
4. Join the server again and notice that the craft may have disintegrated or left behind chunks at the previous locations

**Expected behavior**
Crafts should neither disintegrate nor leave blocks behind at the previous location

**Screenshots**
![2020-04-02_13 33 11](https://user-images.githubusercontent.com/11066794/78252034-832ea000-74f2-11ea-9e6e-63f0c9ccd466.png)
![2020-04-02_13 34 25](https://user-images.githubusercontent.com/11066794/78252039-845fcd00-74f2-11ea-8e0a-9edb92b0d15a.png)
![2020-04-02_14 37 06](https://user-images.githubusercontent.com/11066794/78252042-8590fa00-74f2-11ea-8bef-1a488563c739.png)

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 latest build]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [e.g. 1.12.2]

**Additional context**

**Comment by cccm5** [comment]
Save the world before you restart the server - this is basically unavoidable as far as I know.

**Comment by TylerS1066** [comment]
Could movecraft trigger a world save on disable?

**Comment by cccm5** [comment]
Possibly, but that could cause issues and seems rather unsafe to me - it *should* be happening automatically. What version of minecraft and what server software is this happening on?

**Comment by TylerS1066** [comment]
Personally I confirmed this on both AP Build and AP Testing, which are 1.10.2 spigot.  It rarely happens on Build but happens almost constantly on Testing.

**Comment by eirikh1996** [comment]
> Possibly, but that could cause issues and seems rather unsafe to me - it _should_ be happening automatically. What version of minecraft and what server software is this happening on?

I tested it on 1.12.2. With this fork

**Comment by cccm5** [comment]
Spigot or paper?

**Comment by eirikh1996** [comment]
> Spigot or paper?

This was on Spigot
