### ISSUE TITLE
Newer versions?

### ISSUE THREAD

**Issue by Grievous07** [APDevTeam/Movecraft#254]
I've seen this question a lot, but have been unable to find any clear answers. 
"How are some people getting movecraft to work on their 1.14.x servers, while I can only seem to get it on 1.12?"
I run a small family/friends server that we all love to play movecraft together. But are saddened by not having features like the different trap doors, walls, and other new blocks that make builds look much prettier. I've been holding the server back, as movecraft is the only plugin I have that doesn't work on 1.15.X
I'd really appreciate if someone helped me get movecraft to work on my server while updating to at least a 1.14.4 server version. Thank you so much!

**Comment by TylerS1066** [comment]
@eirikh1996 currently has a fork that is 1.15.x compatible, which you can find here:
https://github.com/eirikh1996/Movecraft

(newest releases here: https://github.com/eirikh1996/Movecraft/releases)


Upstream currently supports 1.10.x, 1.11.x, and 1.12.x but we are hoping to import newer version support in the future.

**Comment by Grievous07** [comment]
thanks!

**Comment by HamnHamnilton** [comment]
> @eirikh1996 currently has a fork that is 1.15.x compatible, which you can find here:
> https://github.com/eirikh1996/Movecraft
> 
> (newest releases here: https://github.com/eirikh1996/Movecraft/releases)
> 
> Upstream currently supports 1.10.x, 1.11.x, and 1.12.x but we are hoping to import newer version support in the future.

I'm new to the plugin world with using forks. How would I use this? To get movecraft on my 1.15,x server?

**Comment by Grievous07** [comment]
@HamnHamnilton HamnHamnilton
Go to the github link he gave, get the jar file for the plugin, and upload it to your server. I can help more if I know what hosting service you're using.

**Comment by HamnHamnilton** [comment]
I'm using shockbyte, it uses the multicraft 2 panel. I uploadloaded the jar to my plugin directiory, however the error I get from the server is that an internal error occurred while attempting to perform this command. Shows up red in the /pl list

**Comment by HamnHamnilton** [comment]
> @HamnHamnilton HamnHamnilton
> Go to the github link he gave, get the jar file for the plugin, and upload it to your server. I can help more if I know what hosting service you're using.

Also on the top github link... I can't even find the jar. It looks like the inside of a jar to me...

**Comment by TylerS1066** [comment]
> I'm using shockbyte, it uses the multicraft 2 panel. I uploadloaded the jar to my plugin directiory, however the error I get from the server is that an internal error occurred while attempting to perform this command. Shows up red in the /pl list

I'd recommend heading over to [Eirik's issues page](https://github.com/eirikh1996/Movecraft/issues) and posting your startup logs there so he can help you debug any startup issues.

This is also the link to the releases of Eirik's plugin, which is were you can find a jar under assets: https://github.com/eirikh1996/Movecraft/releases
