### ISSUE TITLE
How do i add Weapons to my movecraft Airship?

### ISSUE THREAD

**Issue by N-gct** [APDevTeam/Movecraft#255]
How do i add weapons to my Movecraft Airship? I have a small server and I do not know how i can have weapons that destroy stuff on my airship? I have the movecraft plugin

**Comment by cccm5** [comment]
There's two typical approaches. You can either use redstone cannons on your airships, or you can use the [cannons plugin](https://www.spigotmc.org/resources/cannons.56764/) for simple plugin based cannons.
