### ISSUE TITLE
2 Questions: How to use Turrets, and How to add custom ship types

### ISSUE THREAD

**Issue by N-gct** [APDevTeam/Movecraft#256]
How do I use turrets? i saw them in the types file. What do they do, and how do they work?

Also, how do i add a custom ship type? I want to add one with this config:
`name: Hyperring
maxSize: 5000
minSize: 300
allowedBlocks:
        - ALL_WOOD
        - WATER
        - LAVA
        - ALL_LOG
        - all_planks
        - GLASS
        - DISPENSER
        - NOTE_BLOCK
        - ALL_BED
        - sticky_piston
        - piston_head
        - all_wool
        - all_slab
        - BOOKSHELF
        - TORCH
        - FIRE
        - oak_stairs
        - birch_stairs
        - jungle_stairs
        - spruce_stairs
        - chest
        - redstone_wire
        - nether_brick_stairs
        - all_stairs
        - furnace
        - all_sign
        - ladder
        - all_door
        - lever
        - all_pressure_plate
        - redstone_torch
        - redstone_wall_torch
        - all_button
        - all_fence
        - netherrack
        - glowstone
        - cake
        - repeater
        - all_stained_glass
        - all_trapdoor
        - all_stone_bricks
        - iron_bars
        - glass_pane
        - all_fence_gate
        - enchanting_table
        - brewing_stand
        - cauldron
        - dragon_egg
        - redstone_lamp
        - ender_chest
        - TRIPWIRE_HOOK
        - EMERALD_BLOCK
        - BEACON
        - FLOWER_POT
        - all_SKULL
        - all_ANVIL
        - TRAPPED_CHEST
        - COMPARATOR
        - daylight_detector
        - REDSTONE_BLOCK
        - HOPPER
        - all_QUARTZ_BLOCK
        - all_rail
        - DROPPER
        - ALL_STAINED_GLASS_PANE
        - SLIME_BLOCK
        - ALL_CARPET
        - COAL_BLOCK
        - END_STONE_BRICKS
        - barrel
        - sea_lantern
        - smooth_stone
        - all_CONCRETE
        - crafting_table
		- all_stairs
		- 

canFly: true
rotateAtMidpoint: true
allowCannonDirectorSign: false
allowAADirectorSign: false
canCruise: true
cruiseSpeed: 0.3
cruiseSkipBlocks: 100
maxHeightLimit: 130
maxHeightAboveGround: 46
collisionExplosion: 0.0
fuelBurnRate: 0.3
explodeOnCrash: 2.0
sinkSpeed: 3.0
overallSinkPercent: 97.0
detectionMultiplier: 20.0
underwaterDetectionMultiplier: 2.0
smokeOnSink: 1
keepMovingOnSink: true
speed: 0
tryNudge: false
sinkPercent: 99.0
flyblocks:
    all_concrete: #wool represents lift
        - 10.0
        - 100.0
    sea_lantern: #lantern represents hyperdrive
        - 10.0
        - 100.0
    [CHEST,TRAPPED_CHEST, barrel]: # limit chests to make big airships important for merchant missions
        - 0.0
        - N2
    [DISPENSER,HOPPER]: # dispensers and hoppers can be used for inventory too, so limit them as well
        - 0.0
        - 50.0
    REDSTONE_BLOCK: # redstone represents engines
        - 3.0
        - 100.0
    ANVIL: # anvils are OP armor, so limit it
        - 0.0
        - 1.0
    OBSIDIAN: # so is obsidian
        - 0.0
        - 20.0
    WATER: # so is water
        - 0.0
        - 20.0
`

**Comment by TylerS1066** [comment]
To create a new craft type you would paste that into a text file and save it as `Hyperring.craft`.

You can see turrets being demoed in this video here: https://www.youtube.com/watch?v=YbOezZS06oU

**Comment by N-gct** [comment]
Thanks. Also, is there any way to reduce lag?
