### ISSUE TITLE
Console error upon piloting any craft in latest beta 3

### ISSUE THREAD

**Issue by jamesol1** [APDevTeam/Movecraft#260]
Console error upon attempting to pilot any craft.
_https://pastebin.com/qv3v3mJQ_

Versions:
- movecraft beta 3 (one uploaded today)
- paperspigot 1.12.2

**Comment by cccm5** [comment]
What version of java are you running?

**Comment by jamesol1** [comment]
> What version of java are you running?

![image](https://user-images.githubusercontent.com/24861741/80314498-ac88d600-87e9-11ea-9190-5238e1e3ee61.png)

**Comment by cccm5** [comment]
Hm, I'm not sure exactly what's happening. I think its something to do with paper modifying the classpath but I'm not certain.
