### ISSUE TITLE
Phantom lights left behind everywhere

### ISSUE THREAD

**Issue by LeonsonLim** [APDevTeam/Movecraft#261]
There will be phantom lights left behind where light sources once were before the craft with said light sources was moved.
Phantom lights are apparent light sources that only contain air block.
Phantom lights behave randomly. Sometimes they will disappear when the player quits and logs back in, indicating a client side visual bug. And sometimes they will persist and only disappear when a block is placed at the exact spot where it is.
It is observed that sometimes once the craft is moved, the light source blocks on the craft become "dark", i.e. cease to emit light to the surrounding blocks. This is when the phantom lights are left behind at the original positions of the light sources. And randomly, the light sources will be updated every time the craft moves, i.e. emitting light again, thus repeating the cycle of leaving behind phantom lights.

**Comment by cccm5** [comment]
What version of movecraft and minecraft are you using?

**Comment by LeonsonLim** [comment]
The Movecraft version used is Movecraft 7.0.0 beta 3 hotfix.
The Minecraft version used for the server is 1.11.2.

**Comment by LeonsonLim** [comment]
This occurrence seems to have persisted as of Movecraft version 7.0.0, with the same Minecraft version of 1.11.2.

**Comment by TylerS1066** [comment]
Due to our focus on 8.0, we are going to close this.  If the issue persists on 8.0 after a full release, feel free to open a new issue.
