### ISSUE TITLE
Bug Light in 1.15

### ISSUE THREAD

**Issue by SpiderDeluxe** [APDevTeam/Movecraft#276]
**Bug Light**
During the movement of my ships, there is the buggano of the shadows of the blocks and the effects of the terrifying effects

**To Reproduce**
1. start a medium-sized ship
2. you make it move a little
3. See error

**Expected behavior**
I expect this bug to be fixed, as it really is a blow to aesthetics

**Screenshots**
![2020-06-06_12 09 56](https://user-images.githubusercontent.com/30773632/83941840-d1ac3380-a7ee-11ea-82f2-81ecdd560532.png)

**Versions (please complete the following information):**
 - Movecraft: Ultimate prerelease
 - Minecraft: 1.15.2

**Comment by TylerS1066** [comment]
This repository does not have support for 1.15.2, I believe you may be looking for eirik's fork found [here](https://github.com/eirikh1996/Movecraft).  I recommend going and posting this issue on his repository.

**Comment by SpiderDeluxe** [comment]
> This repository does not have support for 1.15.2, I believe you may be looking for eirik's fork found [here](https://github.com/eirikh1996/Movecraft). I recommend going and posting this issue on his repository.

I use his repository, I was really careless, thanks for the support
