### ISSUE TITLE
Redstone on movement

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#281]
**Describe the bug**
On movement of a craft redstone stops updating.  This was a crucial addition to Movecraft 6.0 and I would hate to see it disappear for 7.0.

**To Reproduce**
1. Press a button on a moving craft

**Expected behavior**
Button resets itself after the correct amount of time has elapsed

**Versions (please complete the following information):**
 - Movecraft: beta 4

**Comment by cccm5** [comment]
For some more info, does the button not un-press or?

**Comment by TylerS1066** [comment]
It does not, neither do repeaters or comparators update.

**Comment by DalekCraft2** [comment]
I also experience this. For clarity and as an example, a button can be pressed whilst a ship is moving, but, if the ship moves before it has finished being pressed, it will stay pressed until broken and replaced.

**Comment by drfiveminusmint** [comment]
Placing a sign next to a comparator clock or torch clock will allow it and all connected repeaters to function while moving. I'm currently trying to figure out what causes this, if anyone else has any knowledge that would be appreciated.

**Comment by TylerS1066** [comment]
> Placing a sign next to a comparator clock or torch clock will allow it and all connected repeaters to function while moving. I'm currently trying to figure out what causes this, if anyone else has any knowledge that would be appreciated.

Does this still function in Movecraft 7?  I was aware that this worked in 5 and lower due to the sign being updated on movement or something, but was unaware it worked in 7.

**Comment by HumorousFool** [comment]
It does

**Comment by TylerS1066** [comment]
As mentioned in #281 and #300, this bug has far wider effects than first discovered.

**Comment by cccm5** [comment]
Fixed with a538bb5fa41388a3e020df14e4186df46d6a6609
