### ISSUE TITLE
/assaultinfo NPE

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#295]
**Describe the bug**
Assaultinfo generates an NPE on line 72, I believe it to be malformed siege configs causing this.

**Comment by cccm5** [comment]
is `SiegeEnable` true in the movecraft config?

**Comment by TylerS1066** [comment]
Originally no, but now it is and still throws an NPE.

**Comment by cccm5** [comment]
interesting, is it happening in the same place and or is there an error in the startup logs? that line would incidate that the siege manager is failing to load which normally should only happen when siege is disabled.

**Comment by TylerS1066** [comment]
It happens anytime anyone runs /assaultinfo, no issues in startup logs.

I'll do more debugging in a little bit.

**Comment by TylerS1066** [comment]
Figured it out, I was using EnableSiege not SiegeEnable in the config.yml
