### ISSUE TITLE
Torpedo not exploding with block contact

### ISSUE THREAD

**Issue by duder123** [APDevTeam/Movecraft#303]
**Describe the bug**
Using the original torpedo file, after updating to movecraft for 1.16.1 torpedos no longer explode after they fly into a block. They all stop 1 block away from the contact point.

**To Reproduce**
1. Create a torpedo
2. Launch it
3. Stops before meeting contact

**Expected behavior**
I expect it to explode and destroy a small area

 - Movecraft: [First release for 1.16.1]

 - Minecraft [1.16.1]

**Comment by TylerS1066** [comment]
This repository does not have support for 1.16, I believe you are looking for eirik's fork:
https://github.com/eirikh1996/Movecraft

**Comment by duder123** [comment]
alright thanks
