### ISSUE TITLE
Help needed, trying to add blocks to config

### ISSUE THREAD

**Issue by MRillyt** [APDevTeam/Movecraft#317]
I'm adding blocks by their new 1.15 ids that the latest movecraft supports like stone bricks under  - stone_bricks and it never works with movecraft crashing and errors surrounding it. I'm not sure if this is a movecraft issue or there is another file i need to edit to allow stone bricks or other blocks to be added to movecraft ship types. If u really want to help in our server and project closely my discord is illyt#6211 if not any response or help would be much appreciated.

**Comment by TylerS1066** [comment]
This repository does not support 1.15, I believe you are looking for [eirik's fork](https://github.com/eirikh1996/Movecraft).
