### ISSUE TITLE
Entities? 7.0.0_pre-release_3

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#32]
I thought Entities were fixed in this version of Movecraft? the 7.0.0_pre-release_3 finally got the plugin able to work with PaperSpigot, no longer crashing out, but when I put some sheep in a ship and cruise, they just stay where they are and dont stay with the ship.

**Comment by cccm5** [comment]
It was added in a pull request, but the code quality leaves a lot to be desired. If the code quality improves, I'll add it - but if not I'll add it myself before the final release.

**Comment by FrozenBeard** [comment]
Dope, its the most requested thing from my players, being able to move their animals about and stuff =D

**Comment by cccm5** [comment]
Done
