### ISSUE TITLE
Good speeds

### ISSUE THREAD

**Issue by MRillyt** [APDevTeam/Movecraft#332]
I'm working on a server that will have multiple other plugins such as SF called nemesis.mc
I've set up the config to work with multiple ship types based of WW2.
When it comes to speed I'm not sure what's good or not?

so for up to 2000 blocks what should be a good speed/cruise speed ?
so for up to 5000 blocks what should be a good speed/cruise speed ?
so for up to 7000 blocks what should be a good speed/cruise speed ?
so for up to 10,000 blocks what should be a good speed/cruise speed ?

server has 20G ram but has SF and some other plugins.
an answer before Sunday(server release) would be amazing

**Comment by mwkaicz** [comment]
Honestly this is not only about RAM. By my opinion it's much more about CPU. It must recount and validate each position for new blocks, RAM only keeps blocks info.  Also it depends on count of active crafts at the same time.

more important is Speed

... cruiseSkipBlocks is mostly up to you 
- it isn't too much relevant for this, it only says how much blocks should be skipped
- doesn't effect how often it's possible to do it - but it affects how many blocks must be replaced per each step/skip.

You should remember that blocks are moved in line of the movement direction. Blocks are changing only when is necessary to replace them. When you have line of same block types, then only first one (count depends on cruiseSkipBlocks) will be created (air is replaced to the block) and last one will be replaced to the air. All replacement of same block types is ignored.

Conclusion:
- if you have long slim ship, it will be much more effective than short and wide ship ...  
- same for blocktypes, if you have a ship few block types it will be much more effective than ship where is each block different.

I recommend to use only speed (without cruise function) for crafts up to 1k-2k max  ... with some logical rate for your craft types (f.e: tank should be slower than aircraft, big cruiser is slower than fighter, etc.)

For all bigger crafts, especially for those around 5-10k blocks and more you should have speed only 0.5-1, not more - for all crafts and tune only cruiseSkipBlocks.

You should try several tests with more active crafts to find right values for your server. It's hard to say specific values without knowing behavior of your server and other plugins.

**Comment by MRillyt** [comment]
thanks mate really appreciate it
