### ISSUE TITLE
FEATURE REQUEST: Add requirePlayers to the ships so that certain ships require multiple players onboard (within the ship's hitbox)

### ISSUE THREAD

**Issue by wolfebersahd** [APDevTeam/Movecraft#337]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

It would be interesting to have certain ships classes particularly larger ships require multiple players to be piloted successfully. Giving the allure that larger ships need more crew to me manned. This would add a whole new depth to Movecraft ships.

**Describe the solution you'd like**
During pilot checking it can check for playerEntities and if sufficient player entities are detected within the ship's hitbox, it is successfully piloted. If insufficient playerEntities are detected within the hitbox, it fails to pilot, and outputs an "Insufficient crew onboard to pilot this craft. Please have more players on the craft"

Note: I understand that a player could be in the hitbox, then leave the hitbox for the "captain" to continue piloting it solo. And, i'm okay with that, because it's a risk of not being able to re-pilot it later if you release it. Smart players could also have life rafts, or escape pods that can be solo-piloted to get off a ships that is too big for them to pilot alone.

**Comment by TylerS1066** [comment]
This sounds like a great project for a starting dev to learn the Movecraft API by making their own Addon.

As a hint, for the simple solution you could merely register a listener for [CraftDetectEvent](https://github.com/APDevTeam/Movecraft/blob/master/modules/api/src/main/java/net/countercraft/movecraft/events/CraftDetectEvent.java) and use .getCraft.getHitbox() to get the craft's hitbox, and then see if enough of the online players are near the hitbox (using [MathUtils.locIsNearCraftFast()](https://github.com/APDevTeam/Movecraft/blob/c03109ce0bb087f69bb92a8da7219decd5f1fef7/modules/api/src/main/java/net/countercraft/movecraft/utils/MathUtils.java#L95)).

**Comment by TomLewis** [comment]
I would use this, one of my users actually suggested this on my suggestions page!
