### ISSUE TITLE
Status signs are no longer functional

### ISSUE THREAD

**Issue by HumorousFool** [APDevTeam/Movecraft#354]
**Describe the bug**
When adding a flyblock that can be comprised of multiple blocks for example [5, 125, 126] (wood, wooden slabs and wooden double slabs) only the first flyblock in the list is taken into account when calculating it on the status sign.

**To Reproduce**
1. Make craft with a flyblock that has multiple IDs.
2. Pilot that craft and update the status sign.

**Expected behavior**
All block IDs in the list should be counted into the status sign, just like in the sinking calculation.

**Versions (please complete the following information):**
 - Movecraft 7.0 beta 7
 - Java 1.8.0_271
 - Minecraft/Paper 1.12.2

**Comment by TylerS1066** [comment]
As of #459, the status sign is no longer functional.  #463 looks like a promising replacement, and we will continue discussion on the implementation on that PR.

**Comment by TylerS1066** [comment]
I've updated the title to reflect the current status of status signs since I plan on using this issue to track the problem.
