### ISSUE TITLE
Ships cannot move up and diagonally at the same time

### ISSUE THREAD

**Issue by HumorousFool** [APDevTeam/Movecraft#356]
**Describe the bug**
When you face diagonally up your ship will ether go straight up or diagonally horizontally. I believe this has to do with the changes made in the gearshift system.

**To Reproduce**
1. Pilot a craft
2. Face around 45 degrees up and diagonally
3. Click to move

**Expected behavior**
Ships will move one block on the X Y and Z axis

**Versions (please complete the following information):**
 - Movecraft: 7.0.0 beta 8
 - Minecraft 1.10.2

**Comment by TylerS1066** [comment]
I made a few comments on the gearshift PR relating to eirik's changes to the stick movement code, and this is probably because of it.  A simple fix would be to revert the changes to that portion of the code.

**Comment by TylerS1066** [comment]
This was fixed when #357 was merged.
