### ISSUE TITLE
Undefined behaviour on standing cruise signs

### ISSUE THREAD

**Issue by drfiveminusmint** [APDevTeam/Movecraft#358]
**Describe the bug**
Standing cruise signs behave in very unpredictable ways, causing a craft to cruise in seemingly random directions. I noticed this bug first with CruiseOnPilot crafts but it's also present with normal cruise signs.

**To Reproduce**
1. Place a standing cruise sign / CruiseOnPilot craft sign facing in different directions.
2. Pilot the ship and attempt to use the cruise sign while facing the ship different directions.

**Expected behavior**
Crafts should have a null (0x00) cruise direction if they cannot find a defined cruise direction.

**Versions (please complete the following information):**
All version info is whatever AP Build Server is running.

**Additional context**
This should be fixable by simply causing all standing cruise signs to set a CruiseDirection of 0x00.

**Comment by TylerS1066** [comment]
Would setting a null cruise direction remove the ability for standing signs on a cruiseOnPilot to work as both a diagonal and vertical craft?

**Comment by drfiveminusmint** [comment]
cruiseOnPilot crafts don't *really* have this feature currently, at least not in a way that's controllable by players. Having a null cruise direction would cause CruiseOnPilot crafts to simply obey their cruiseOnPilotVertMove value, and players can use a secondary (wall) sign to make them dual-pilotable. Currently, the crafts will either simply obey their cruiseOnPilotVertMove value or cruise in a pseudo-random direction.

**Comment by drfiveminusmint** [comment]
Which behavior they exhibit is determined by many factors including super-craft facing, longest axis, and position of the sign, and is not meaningfully controllable by players.

**Comment by TylerS1066** [comment]
> Having a null cruise direction would cause CruiseOnPilot crafts to simply obey their cruiseOnPilotVertMove value, and players can use a secondary (wall) sign to make them dual-pilotable.

Ok, so a null cruiseDirection will make standing signs obey as they should be currently (with only their vertical direction being taken into account), and wall signs will still work properly.

**Comment by drfiveminusmint** [comment]
Correct

**Comment by HumorousFool** [comment]
#365 should fix this
