### ISSUE TITLE
Adding new block types to boat type files crashes the plugin

### ISSUE THREAD

**Issue by WolfyRed** [APDevTeam/Movecraft#368]
**Describe the bug**
When you go into a boat type file, where it reads all of the types of blocks the boat can have, it will not behave like it should when you add new block types to the boat type.

**To Reproduce**
1. Go to `plugins/Movecraft/types/Ship.craft`
2. Scroll to the end of the block ID types
3. Add a completely new block type, while keeping the same text structure as the block type above
4. IT SPAMS ERRORS AND BREAKS THE PLUGIN.

**Expected behavior**
Just... add a brand new completely fine block that gets pushed by pistons into the block types for the craft.

**Versions (please complete the following information):**
 - Movecraft: 7.0.0_beta_8
 - Java: Java 11.0
 - Minecraft: Final build for 1.12.2

**Additional context**
I literally just added reversed Daylight sensor, that's it. The original Daylight sensor works just fine, and it's in the block types already, so adding the reversed type should not be a hassle.

**Comment by HumorousFool** [comment]
Could you provide the craft file?

**Comment by WolfyRed** [comment]
The one that works: [Ship.craft.txt](https://github.com/APDevTeam/Movecraft/files/5975257/Ship.craft.txt)

The one I altered with more Block IDs: [Ship_2.craft.txt](https://github.com/APDevTeam/Movecraft/files/5975258/Ship_2.craft.txt)

**Comment by WolfyRed** [comment]
The altered one has more block IDs by the way because I was trying to see if putting them in order may fix the problem, it didn't.

**Comment by HumorousFool** [comment]
I have to view this on my phone so I'm not sure but to me it looks like some of those blocks are over indented in the file

**Comment by WolfyRed** [comment]
> I have to view this on my phone so I'm not sure but to me it looks like some of those blocks are over indented in the file

Not sure about that but what about this?
[Ship_3.craft.txt](https://github.com/APDevTeam/Movecraft/files/5976686/Ship_3.craft.txt)

![image](https://user-images.githubusercontent.com/66114400/107863632-dfa56000-6e23-11eb-94b6-fe45f87c5686.png)
![image](https://user-images.githubusercontent.com/66114400/107863641-ecc24f00-6e23-11eb-93e7-47c0be03648d.png)

**Comment by TylerS1066** [comment]
> The one I altered with more Block IDs: [Ship_2.craft.txt](https://github.com/APDevTeam/Movecraft/files/5975258/Ship_2.craft.txt)

This file is not valid YAML, it appears to have an issue with line 95 having a tab character.  In the future use an online YAML parser if it has issues.

**Comment by WolfyRed** [comment]
> > The one I altered with more Block IDs: [Ship_2.craft.txt](https://github.com/APDevTeam/Movecraft/files/5975258/Ship_2.craft.txt)
> 
> This file is not valid YAML, it appears to have an issue with line 95 having a tab character. In the future use an online YAML parser if it has issues.

psssst... How do I do that? Like this?

Or is there some other way? Because I've run out of ideas :T 

![image](https://user-images.githubusercontent.com/66114400/107864334-26e21f80-6e29-11eb-9f82-90d9e1cc17cf.png)

**Comment by TylerS1066** [comment]
You will want to use space characters such that the indentation is the same:
```
        - 173
        - 178
```

I recommend changing notepad++ to use spaces instead of tabs to avoid this in the future,

**Comment by WolfyRed** [comment]
> You will want to use space characters such that the indentation is the same:
> 
> ```
>         - 173
>         - 178
> ```
> 
> I recommend changing notepad++ to use spaces instead of tabs to avoid this in the future,

It worked, closing this issue

**Comment by WolfyRed** [comment]
What's an invalid
