### ISSUE TITLE
Entities not moving with boat

### ISSUE THREAD

**Issue by WolfyRed** [APDevTeam/Movecraft#370]
**Describe the bug**
My friend wanted passengers in his boat. When he started the boat, the passengers (villagers) just went through the boat.

**To Reproduce**
1. Build a boat (If you haven't already)
2. Put entities into the boat besides players
3. Get the boat moving
4. Watch the non-player entities phase through the boat

**Expected behavior**
The villagers to stay on the boat in the same spot they were standing, as players do.

**Screenshots**
![2021-02-14_03 00 12](https://user-images.githubusercontent.com/66114400/107871596-fde57d00-6e70-11eb-8ba0-c2451997f450.png)
![2021-02-14_03 01 18](https://user-images.githubusercontent.com/66114400/107871597-00e06d80-6e71-11eb-8700-4920da16ddc9.png)

**Versions (please complete the following information):**
 - Movecraft: 7.0.0_beta_8
 - Java: Java 11.0
 - Final build for 1.12.2

**Additional context**
We tried boats and minecarts too, then put the villagers inside of them, as if sitting in a seat, not moving at all. Those entities just phased outside of the boat too.
*That excludes the question "Were the villagers moving too fast?" if you were gong to ask it.*

**Comment by WolfyRed** [comment]
_If you're wondering why the ship is made of hard iron, it is because we wanted to build steam boats, in which I had to replace the main block to use for `Ship.craft` with Iron._

**Comment by HumorousFool** [comment]
Have you set onlyMovePlayers to false in your craft file?

**Comment by WolfyRed** [comment]
> Have you set onlyMovePlayers to false in your craft file?

I do not see that option in the `.craft` file.

**Comment by WolfyRed** [comment]
> Have you set onlyMovePlayers to false in your craft file?

[Ship.craft.txt](https://github.com/APDevTeam/Movecraft/files/5977609/Ship.craft.txt)
Tell me if you see that option in this config

**Comment by TylerS1066** [comment]
[This page](https://github.com/APDevTeam/Movecraft/wiki/Type-File) in the wiki describes all the options available in the .craft type files, except those which were recently added.

**Comment by WolfyRed** [comment]
> [This page](https://github.com/APDevTeam/Movecraft/wiki/Type-File) in the wiki describes all the options available in the .craft type files, except those which were recently added.

Ahem. If any of those options don't exist in a `.craft` file, can they be implemented in a new line?

**Comment by TylerS1066** [comment]
Yes

**Comment by WolfyRed** [comment]
> Yes

Ok then I will try it
