### ISSUE TITLE
Is there a boat type that moves fast?

### ISSUE THREAD

**Issue by WolfyRed** [APDevTeam/Movecraft#371]
I've made a small boat, and I expect it to move fast. Boat type "Ship" is slow, which makes sense since it is meant for big ships, but I don't see any boat types that support fast movement.

What I'm looking at:

![image](https://user-images.githubusercontent.com/66114400/107871633-60d71400-6e71-11eb-9a12-aeffe25c68a9.png)

**Comment by WolfyRed** [comment]
_The edit was replacing the word "many", with "any"_

**Comment by HumorousFool** [comment]
You should be able to change speed or cruiseSpeed to make any craft faster
