### ISSUE TITLE
Craft mid point changes after turning

### ISSUE THREAD

**Issue by HumorousFool** [APDevTeam/Movecraft#372]
**Describe the bug**
The craft's mid point changes after turning on a craft that is an even number of blocks long/wide

**To Reproduce**
1. Make a craft that rotates from mid-point
2. Stand in the middle of your craft
3. Turn with a helm sign
4. Notice how your coordinates change

**Expected behavior**
The craft's mid point should be at the same coordinates after turning.

**Versions (please complete the following information):**
 - Movecraft: 7.0.0 beta 9
 - Java JDK 15
 - Minecraft 1.12.2

**Additional context**
This is a huge issue for plugins like Movecraft-AutoSign that rely on relative locations.

**Comment by cccm5** [comment]
What is the point you are treating as the midpoint for rotation?

**Comment by HumorousFool** [comment]
craft.getHitBox().getMidPoint()

**Comment by HumorousFool** [comment]
Ok so I realized I can just get the new hitbox from the event and therefore this is a minor issue. It does happen so I'm not sure if I should close it.

**Comment by cccm5** [comment]
There is no guarantee that the mid point of a hitbox is consistent in the API under rotation.
