### ISSUE TITLE
Update the FuelTypes

### ISSUE THREAD

**Issue by KELYTheM** [APDevTeam/Movecraft#374]
Movecraft: beta 37
I am trying to add custom fuel types for Movecraft crafts but can't get it to work. So I asked around and it seems like it is outdated..?

I tried adding the following to the config.yml in the very bottom but it still say "Out of fuel" in game when the objects are placed in the furnace:
FuelTypes:
    lava_bucket: 30.0
    stick: 1.0
    oak_sapling: 1.0
    spruce_sapling: 1.0
    birch_sapling: 1.0
    jungle_sapling: 1.0
    acacia_sapling: 1.0
    dark_oak_sapling: 1.0

**Comment by cccm5** [comment]
Please follow the issue template. It's important to know what version of the plug-in you are running.

**Comment by KELYTheM** [comment]
> Please follow the issue template. It's important to know what version of the plugin you are running.

Sorry added it to the message. Using beta 37

**Comment by KELYTheM** [comment]
> > Please follow the issue template. It's important to know what version of the plugin you are running.
> 
> Sorry added it to the message. Using beta 37

nvm I'm on the wrong movecraft issue report

**Comment by cccm5** [comment]
You are not using this repositories version of movecraft. I recommend checking your logs to see if there are any errors. If not, report it to the fork you are using.
