### ISSUE TITLE
Water based ships leave holes in water.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#38]
Ive used movecraft long enough to have seen this bug before in early versions of the plugin.
I was trying out a new 10k ship and realized it was leaving massive chunks in the water.
![2018-02-11_23 12 17](https://user-images.githubusercontent.com/144046/36080043-03c4eb76-0f82-11e8-9edb-1098b4750da1.png)

**Comment by FrozenBeard** [comment]
I think it was compatibility mode, I forgot to toggle it when I upgraded my test server in the config, running again with a reboot fine.

**Comment by FrozenBeard** [comment]
It does leave shadows in the water though.
![2018-02-11_23 26 12](https://user-images.githubusercontent.com/144046/36080102-fdb25d26-0f82-11e8-8e61-fd1c0a01d1d4.png)

**Comment by FrozenBeard** [comment]
Im going to re-open this as its happening again, on my main server, all ships are leaving gaping holes in the sea.

**Comment by cccm5** [comment]
Could you try the latest release?
