### ISSUE TITLE
Exponential Ticks

### ISSUE THREAD

**Issue by SatireShadow** [APDevTeam/Movecraft#383]
**Describe the bug**
A clear and concise description of what the bug is. Exponentially movecraft starts with sending 1 spike, then after 10-15 mins 2 spike, and it just exponentially grows until restart causing major lag spikes. 

**To Reproduce**
1. Use the plugin
2. get a spike tracker like react
3. restart 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24847129/110087192-324daa00-7d48-11eb-85f8-578cbad2274a.jpeg)
**Versions (please complete the following information):**
 - Movecraft: 7.0.0 Beta 37
 - Java 11
 - Minecraft 1.16.5

**Additional context**

**Comment by cccm5** [comment]
Please report this to the repo of the version you are using
