### ISSUE TITLE
Make CraftDetectEvent cancellable

### ISSUE THREAD

**Issue by drfiveminusmint** [APDevTeam/Movecraft#387]
**Is your feature request related to a problem? Please describe.**
Currently, CraftDetectEvent is not cancellable. This creates issues for those wanting to create addons that stop players from piloting a craft.

**Describe the solution you'd like**
Cancelling a CraftDetectEvent should stop the piloting of a craft.

**Comment by HumorousFool** [comment]
It already is

**Comment by drfiveminusmint** [comment]
ah, I was running off an old version of Movecraft. Silly me!
