### ISSUE TITLE
Water ship sinking crashes Redstone/Pistons through entire server for 10 mins.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#40]
This is a hard one to diagnose, but Ill try and explain it best I can, On multiple occasions since moving to this version of Movecraft Redstone gets temporarily disabled server-wide, I *think* its when a ship sinks, all redstone is disabled, pistons stop working server-wide, and the ship isn't released, ./craftreport shows the ships still piloted after its sunk, but the person cannon release it, it says they have no ship piloted, this gets stuck for about 10 mins with everything halted, and then goes back to normal.

**Comment by cccm5** [comment]
Fixed
