### ISSUE TITLE
ProtectionStones support

### ISSUE THREAD

**Issue by Pvprod34** [APDevTeam/Movecraft#405]
Hi guys! i was wondering if you guys could add compatibility with ProtectionStones. It is a block placement based protection system which i think would work really nicely with movecraft type servers. Allows players to place blocks and have a makeshift protection they can break and move.
https://www.spigotmc.org/resources/protectionstones-updated-for-1-13-1-16-wg7.61797/

I tried it out and noticed you can move movecraft vehicles inside protection regions, even if you cant build/break in them.

Many thanks for your work on the plugin!

**Comment by TylerS1066** [comment]
It looks like ProtectionStones uses WorldGuard as a backing plugin for the actual protection handling.  As of [7.0.0](https://github.com/APDevTeam/Movecraft/releases/tag/7.0.0) we moved the last external plugin dependency out of Movecraft, and instead are using addons.  The WorldGuard integration was moved to [Movecraft-WorldGuard](https://github.com/APDevTeam/Movecraft-WorldGuard) which has support for 7.0.0 and experimental support for the 8.0 alphas.
