### ISSUE TITLE
Water ships, Sinking ships do not "mould" around terrain they land on.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#41]
When water based ships, or any ships for that matter sink, their blocks do not "mould" around terrain, so when they crash they end up just keeping their ship shape and just, like float above where they crashed from the top block they landed on, this looks awful in comparison to the latest version of Movecraft that makes ship wrecks look like shipwrecks moulding into the terrain.

**Comment by hmmcrunchy** [comment]
Hiya I’d  second this 

If it’s possible to do that would be handy as the sort of structure collapse on the ground makes much better wreckage

**Comment by cccm5** [comment]
Ya this is something i need to fix before release, it's definitely being re-added. I was also thinking about changing it to cause the ship to explode into many different directions (instead of just falling down), I'm open to opinions on that though

**Comment by hmmcrunchy** [comment]
That sounds pretty epic :)

**Comment by cccm5** [comment]
This is fixed

**Comment by FrozenBeard** [comment]
There isnt really any shipwrecks left, blocks tend to just vanish into the blocks they hit on a sea floor. I can create a video if you want of the way the Movecraft 6 does it?
