### ISSUE TITLE
"ManOverboardTimeout:" isn't adjustable

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#412]
**Describe the bug**
Editing the time that a craft can stay piloted without the pilot being onboard has no effect.

**To Reproduce**
1. Set a small amount of time to "ManOverboardTimeout:"
2. Observe the time it takes before releasing after leaving the craft.
3. Set a large amount of time to "ManOverboardTimeout:"
4. Observe the time it takes before releasing after leaving the craft.

**Expected behavior**
Manoverboard Timeout to be adjustable and allow for a customizable amount of time allowed while off a craft before releasing it.

**Screenshots**

**Versions (please complete the following information):**
 - Movecraft: 8.0.0-a.2
 - Java 11 - OpenJ9
 - Minecraft e.g. 1.16.5

**Additional context**
Config File
```Locale: en
CompatibilityMode: false
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
TracerMinDistance: 60
PilotTool: STICK
ManOverboardTimeout: 860
ManOverboardDistance: 5000
FireballLifespan: 5
ProtectPilotedCrafts: true
DisableSpillProtection: false
DisableIceForm: true
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: true
FadeWrecksAfter: 600
FadeTickCooldown: 20
FadePercentageOfWreckPerCycle: 10.0
ExtraFadeTimePerBlock:
  CHEST: 600
  TRAPPED_CHEST: 600
  DISPENSER: 600
  DROPPER: 600
  FURNACE: 600
BlockQueueChunkSize: 200000
MaxRemoteSigns: -1
CraftsUseNetherPortals: true
ForbiddenRemoteSigns:
- Mounted
- Denied
- '[private]'
RequireNamePerm: false
GeneratedDatapack: true
FuelTypes:
    263: 5.0```

**Comment by cccm5** [comment]
So as it turns out, the core cause of this issue is that `ManOverboardTimeout` is actually a timeout for the use of the manoverboard command, rather than a timeout for auto releasing itself. I'll implement a new config option `ReleaseTimeout` to solve this.
