### ISSUE TITLE
[bug] Cannnot turn water based ships "Obstructed" 

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#42]
Updated to the pre-release V4, and now water based ships cannot turn in water (Helm sign), it just shows Obstructed, Things like /cruise east is also broken as its saying obstructed. 

![2018-02-27_13 05 18](https://user-images.githubusercontent.com/144046/36728272-148eb698-1bb8-11e8-97b5-f93080f0559a.png)

As for the holes left behind water ships, it seems as if its fixed, but I will report back after more testing happens, my seas are utterly destroyed its going to take hours to fix my seas :(

![2018-02-27_09 13 14](https://user-images.githubusercontent.com/144046/36728318-3beb5624-1bb8-11e8-9944-b0a4d33f6bec.png)

**Comment by FrozenBeard** [comment]
/rotate right, also does nothing (Obstructed). Rip.

**Comment by FrozenBeard** [comment]
@cccm5

**Comment by Miclebrick** [comment]
Seems like movement in water is almost entirely broken..

**Comment by FrozenBeard** [comment]
I had to backdate to my like 1.9 version of movecraft as my entire server is water based ships... Im hoping someone will fix this!

**Comment by FrozenBeard** [comment]
Please can this be fixed.
Bump.

**Comment by hmmcrunchy** [comment]
hopefully it will but bear in mind these guys  are doing this in spare time for free :)

**Comment by cccm5** [comment]
Real sorry, I've been swamped with school lately. Thankfully I'm on break now so development will be able to resume. This issue is actually a lot more complicated than it appears but I have a solution in mind!

**Comment by cccm5** [comment]
I'm aiming to fix this with the addition of #17, hopefully I'll have something to test soon. It will require minor changes to .craft files (1-2 lines added).

**Comment by FrozenBeard** [comment]
@cccm5 I am itching to get your version live again! The speed improvements are dramatic for large ships, Sinking is a bit sketchy but thats another bug for another time, get these basics fixed!

Got some big plans for expansion of water based ships!

**Comment by FrozenBeard** [comment]
Any updates? I'm still having to use the ancient version of movecraft.

**Comment by Miclebrick** [comment]
BTW frozenbeard you can use fastasyncworldedit and //fixwater to quickly fix issues like that

**Comment by cccm5** [comment]
Fixed!
