### ISSUE TITLE
CruiseOnPilot Lifetime Configurability

### ISSUE THREAD

**Issue by drfiveminusmint** [APDevTeam/Movecraft#420]
**Is your feature request related to a problem? Please describe.**
Server managers may want to configure CruiseOnPilot crafts to have different lifetimes. 

**Describe the solution you'd like**
In Movecraft 7, this was globally configurable, but I think it would be better to have a CruiseOnPilotLifetime field in a craft file (or something similar) to control their lifetime.

**Comment by cccm5** [comment]
I think it'd be a good idea to reconsider the lifetime specification of cruise on pilot in general. Right now its based on time, which is good for things which require player control. If the server hangs for a period of time, it's good to have a real time metric for aborting a craft. In the case of cruiseonpilot however, pilots immediately relinquish control of their craft. Thus, we end up with non-deterministic cruiseonpilot maximum distances, whereas we could instead use something like the max number of movements to yield a much simpler and understandable limiter, while keeping the global time based lifetime as a watchdog in the case of a serious error.

**Comment by TylerS1066** [comment]
To expand upon this with what was suggested in #594, we should also expose the arming time.
