### ISSUE TITLE
Per-craft scuttling toggles 

### ISSUE THREAD

**Issue by galacticwarrior9** [APDevTeam/Movecraft#429]
**Is your feature request related to a problem? Please describe.**

If `/scuttle` is enabled, players can use it on any craft. This is problematic for crafts which need to permit a very wide range of blocks (e.g. 'factories' and 'shipyards') as players could walk to the territory of other players, pilot a building as one of these crafts and then `/scuttle` it to destroy it. Furthermore, server admins may want to prevent some crafts from being scuttled, such as expensive but powerful crafts that should always be at risk of being seized by enemies.

**Describe the solution you'd like**
An `allowScuttle` or similar flag in the craft file which determines whether the craft can be scuttled or not

**Comment by cccm5** [comment]
I think that a better option would be for a permission flag for each craft, akin to rotation and cruising. It would be of the form `movecraft.crafttype.scuttle` where `crafttype` is replaced with the appropriate type. Let me know what you think.

**Comment by TylerS1066** [comment]
> Let me know what you think.

I love this idea.

**Comment by galacticwarrior9** [comment]
Sounds perfect
