### ISSUE TITLE
Make it so direction dependent attached blocks only connect to the craft when facing the craft.

### ISSUE THREAD

**Issue by CaptainPi-PiLabs** [APDevTeam/Movecraft#430]
My main focus is on torches but this also applies to things such as tripwire hooks and ladders.

When a craft is formed it will join these types of blocks even when they aren't connected to the craft. This creates floating torches and floating vehicles.

It would be nice if during the craft formation these types of blocks were only joined to the craft if they were facing towards a block that is part of the craft and not use these blocks to attach further blocks.

**Comment by cccm5** [comment]
Honestly no idea why I never thought of this, I'll look into it
