### ISSUE TITLE
Ships should be able to move through water foliage

### ISSUE THREAD

**Issue by TheHappyHopper** [APDevTeam/Movecraft#433]
**Is your feature request related to a problem? Please describe.**
Ships currently cannot move through blocks like Kelp and seagrass

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Feel free to include images to better explain the feature.
it would be great to have a list of blocks the ships can move through, not stopping your ship from moving because you hit a plant

**Comment by TylerS1066** [comment]
What version are you running of Movecraft?

I assume one of the 8.0 alphas, in which case you should add kelp and seagrass to the [passthroughBlocks](https://github.com/APDevTeam/Movecraft/wiki/Type-File) of your craft types.  We should probably do this to any default submersible or ship type crafts.

**Comment by TheHappyHopper** [comment]
running 8.0 alpha 3, managed to get the ship working by turning off the water requirement, and was testing the ships but i actually couldnt find the passthroughblocks argument, ill check for that now
