### ISSUE TITLE
Cannons resetting after the craft moves 

### ISSUE THREAD

**Issue by acrticsludge** [APDevTeam/Movecraft#436]
**Describe the bug**
Been having a bug where cannons get reset on the move and rotation. it happens on Tank craft(custom ground craft ) and submarine.

**To Reproduce**
No visible errors

**Expected behavior**
I wanted the cannon to not get reset and work properly.

**Screenshots**
None.

**Versions (please complete the following information):**
 - Movecraf: 8 java CI #189 
 - Java JDK 16.0.0
 - Minecraft paper-1.16.5

**Additional context**
none

**Comment by cccm5** [comment]
This is not the movecraft-canons repo (it's already known there however)

**Comment by acrticsludge** [comment]
oops sorry i clicked the wrong link mb (and ok)

**Comment by TylerS1066** [comment]
I've created an issue in the Movecraft-Cannons repo to track this @acrticsludge : https://github.com/TylerS1066/Movecraft-Cannons/issues/9
