### ISSUE TITLE
Timing Stack Error Movecraft 7.0.0

### ISSUE THREAD

**Issue by Themanofpie1** [APDevTeam/Movecraft#437]
**Describe the bug**
Craft does not rotate but entities on board do.

**To Reproduce**
 1. Pilot craft
 2. Click helm sign

**Results**
Entities on board craft will rotate 90 degrees but the craft itself will not.

7.06 17:53:36 [Server] Server thread/INFO [net.countercraft.movecraft.Movecraft]: [Movecraft] Player Themanofpie piloted a craft of type Ship with size 20 at location: 336 x, 161 z
27.06 17:53:37 [Server] Server thread/WARN [net.countercraft.movecraft.Movecraft]: [Movecraft] Task #4070 for Movecraft v7.0.0 generated an exception
27.06 17:53:37 [Server] INFO java.lang.ClassCastException: java.util.TreeSet cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.HashTreeSet
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.compat.v1_12_R1.NextTickProvider.registerWorld(NextTickProvider.java:41) ~[?:?]
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.compat.v1_12_R1.NextTickProvider.getNextTick(NextTickProvider.java:52) ~[?:?]
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.removeTileEntity(IWorldHandler.java:278) ~[?:?]
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.getTiles(IWorldHandler.java:234) ~[?:?]
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.compat.v1_12_R1.IWorldHandler.rotateCraft(IWorldHandler.java:101) ~[?:?]
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.mapUpdater.update.CraftRotateCommand.doUpdate(CraftRotateCommand.java:141) ~[?:?]
27.06 17:53:37 [Server] INFO at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
27.06 17:53:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:045a413]
27.06 17:53:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:045a413]
27.06 17:53:37 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
27.06 17:53:37 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
27.06 17:53:37 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:858) [MinecraftServer.class:?]
27.06 17:53:37 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:730) [MinecraftServer.class:?]
27.06 17:53:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
**27.06 17:53:37 [Server] Server thread/ERROR [global]: TIMING_STACK_CORRUPTION - Report this to the plugin Movecraft(Look for errors above this in the logs) (TimingIdentifier{id=Movecraft:Task: net.countercraft.movecraft.mapUpdater.MapUpdateManager (interval:1)} did not stopTiming)**

**Versions (please complete the following information):**

Movecraft: 7.0.0
Minecraft: Magma 1.12.2

**Additional context**
I feel it could be an issue with the forge hybrid I'm using (Magma).

**Comment by cccm5** [comment]
We don't support forge hybrids
