### ISSUE TITLE
Make requirewatercontact check each movement

### ISSUE THREAD

**Issue by TheHappyHopper** [APDevTeam/Movecraft#439]
**Is your feature request related to a problem? Please describe.**
My Players are able to place a water bucket on the side of their ship (the only type i have active) and fly them around

**Describe the solution you'd like**
Make the requirewatercontact flag check on every movement the ship makes

**Comment by cccm5** [comment]
Duplicate of #404

**Comment by TheHappyHopper** [comment]
> Duplicate of #404

I think you misunderstand, #404 is stating that the craft doesnt work at all
Mine is stating that the ships work even if they aren't touching water when requirewatercontact is set to true

**Comment by cccm5** [comment]
#404 is both, hence its title
