### ISSUE TITLE
Better player teleporting which allows you to teleport the player without affecting rotation

### ISSUE THREAD

**Issue by Miclebrick** [APDevTeam/Movecraft#44]
While adding direct control to my own ships plugin, I discovered a method that allows you to teleport players without messing with their facing direction. This allows them to look around freely while the ship is moving.

Method: ((CraftPlayer) player).getHandle().setPosition(location.getX(), location.getY(), location.getZ());

I can confirm this works on 1.12.2. I expect it'll work on older versions, as well, though I cannot confirm

**Comment by FrozenBeard** [comment]
Sweet. What other features have you added?

**Comment by keough99** [comment]
I believe my navycraft project has a function similar to this or exactly the same

**Comment by Miclebrick** [comment]
@FrozenBeard Well, my starships plugin is private and for my server only. I don't think it'd be appropriate to tell you name of it here. It's almost an entire rewrite, though.

**Comment by FrozenBeard** [comment]
@Miclebrick any chance for a release? I use water based ships only, this version broke turning and the naval version is missing a ton of features. I'm gagging for an updated movecraft and don't want to have to fork it myself!

**Comment by Miclebrick** [comment]
Me? I'm just a random dude lol I have nothing to do with this project

@ccm5

**Comment by Miclebrick** [comment]
I actually would recommend forking it yourself if you have any programming ability

**Comment by FrozenBeard** [comment]
@Miclebrick I don't know any Java :(  Struggling to find a decent updated MoveCraft, would you make yours open?

**Comment by Miclebrick** [comment]
mine doesn't have water anyway, it's a spaceships plugin more than just a Movecraft plugin.

**Comment by cccm5** [comment]
I tried to implement this earlier, but I couldn't get it to work (1.10). I than went into the decompiled source and looked around for what was updating the player on the servers end, and attempted to also set the last positions of the player, as well as calling entity#a. This also didn't work, so I'm at a loss for what actually updates these changes on the server end.

**Comment by Miclebrick** [comment]
https://www.spigotmc.org/threads/teleport-player-smoothly.317416/

**Comment by Miclebrick** [comment]
There was more to it than just what I put here originally

**Comment by cccm5** [comment]
Ok, now that I looked at PlayerConnection I've implemented a similar system in d43c2b43a027e4295afa03128565206178146938. Thanks for bringing this to my attention.
