### ISSUE TITLE
cannons reset when craft is piloted (they still work if you move)

### ISSUE THREAD

**Issue by tskopen** [APDevTeam/Movecraft#443]
**Describe the bug**
When you release/repilot/pilot a craft it resets cannons (but it doesn't if you move! i have movecraft-cannons)

**To Reproduce**
1. setup the cannon
2. pilot the craft
3. try and use the cannon
4. and the cannons reset

**Expected behavior**
you need to repay for a cannon and redo everything (not good when your in combat  and like going on your wing for shooting people and you accidently release your craft and stuff)

**Screenshots**

**Versions (please complete the following information):**
 - Movecraft: Alpha 4
 - Java 16
 - Minecraft paper 1.16.5

**Additional context**
i have towny, movecraft-cannons, movecraft-combat, and cannons
those should be the important plugins you need to know about

**Comment by TylerS1066** [comment]
I've created an issue on the proper repo for you @tskopen
