### ISSUE TITLE
UseGravity doesn't work in the latest 8.0.0 version.

### ISSUE THREAD

**Issue by Mineshaft87** [APDevTeam/Movecraft#444]
**Describe the bug**
UseGravity doesn't seem to work. Land crafts only move down in accordance to the below terrain when stick flying directly downwards, as seen in the later portion of my attached video. **This occurs in non-void environments too.**

**To Reproduce**
Move a land vehicle with **UseGravity: true** off a ledge in cruise mode or stick flying straight ahead and it will fly/glide.

**Expected behavior**
Land vehicles taper to the below ground. 

**video**
https://imgur.com/a/bXzd0I8

**Versions:**
 - Movecraft: 8.0.0-a.3
 - Java 16
 - Minecraft 1.16.5

**Additional context**
No console errors. Not sure if it worked in prior 8.0.0 versions, haven't tested that, may do so later.

**Comment by galacticwarrior9** [comment]
I've been using the fix in [this PR](https://github.com/APDevTeam/Movecraft/pull/334) on production for a few months now and it has eliminated the problem

**Comment by Mineshaft87** [comment]
> I've been using the fix in [this PR](https://github.com/APDevTeam/Movecraft/pull/334) on production for a few months now and it has eliminated the problem

Forgive me my java knowledge is shocking. Did you add the commit from that link into the most recent release or have you installed a version of movecraft dating back to when that commit was added in (if so i'd love to know which version)?

**Comment by TylerS1066** [comment]
#334 was apparently a patch to something with gravity and harvest blocks, not this issue.
