### ISSUE TITLE
Console doesn't report on which craftfile still has an integer ID

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#445]
**Describe the bug**
On the console, movecraft doesn't tell you exactly which craftfile has an integer where an integer block ID shouldn't be. This particularly happens if an integer ID is in DynamicFlyBlock, and ForbiddenBlock.

**To Reproduce**
1. Create a craftfile with varying integer IDs in place in DynamicFlyblock and ForbiddenBlock
2. Try to run movecraft.
3. Check the console.

**Expected behavior**
The console should tell the user in which craftfile an integer ID is in. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68086172/127562970-70f6372a-c9c7-496e-b9f9-2038d4897ecc.png)

**Versions (please complete the following information):**
 - Movecraft: 8 Alpha 4
 - Java 16
 - Minecraft 1.16.5

**Comment by drfiveminusmint** [comment]
I believe this issue was resolved, yes?

**Comment by TylerS1066** [comment]
Nevermind, this has been solved for a while:
```
[16:55:50] [Server thread/ERROR]: [Movecraft] ERROR PARSING CRAFT FILE: 'Airskiff.craft' Entry 7 must be a material for key allowedBlocks
```
