### ISSUE TITLE
Displaced water by piston will no longer push anything.

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#446]
**Describe the bug**
Piston heads seem to functionally destroy water streams, making water no longer flow back to its original position. This means the water does not push anything on that block.

**To Reproduce**
1. Get a regular airship
2. Place water on the airship
3. Put a piston where the head would intersect the water steam with a lever
4. Pilot the airship
5. Activate the piston
6. Stand in the water and you will see that you stop where the piston deleted the water.

**Expected behavior**
Water, even when displaced by a piston should flow back or at least keep its flowing properties.

**Screenshots**
![2021-08-02_02 07 36](https://user-images.githubusercontent.com/68086172/127859489-4d3669e5-990c-4060-94f0-61ba0513659d.png)
Note: The pressure plate item is not moving along where the water stream is supposed to go, whereas it used to work in previous versions.

**Versions (please complete the following information):**
 - Movecraft: 8 Alpha 4
 - Java 16
 - Minecraft 1.17 (uses paper)

**Additional context**

**Comment by TylerS1066** [comment]
I can also repeat this on 1.14.4 paper.
