### ISSUE TITLE
helm sign and direct control dont work?

### ISSUE THREAD

**Issue by PhanaticD** [APDevTeam/Movecraft#45]
sorry if Im missing something just trying this out for the first time today, but helm signs turn into the wheel text but dont actually do anything when clicked? and also direct control i can move around and nothing happens

**Comment by FrozenBeard** [comment]
Turning has been broken since release I have #42 unanswered.

**Comment by cccm5** [comment]
This has been fixed for a while, I should have closed this sooner

**Comment by cccm5** [comment]
The current implementation (which changed in version 6 of the old version) works

**Comment by Appw0905** [comment]
For me direct control lets me move up & down by clicking with the stick, but doesn't move the craft when I move.

**Comment by FrozenBeard** [comment]
How do you use Direct control now?

**Comment by cccm5** [comment]
I'll be writing up a wiki post at some point before the release because it was never properly documented. To be honest I'm not event quite sure anymore.

**Comment by Appw0905** [comment]
Alright thank you for clearing that up, I haven't used movecraft 6 at all, I last used v5 and now your v7.
