### ISSUE TITLE
console spam with Movecraft v7.0.0 and signs not working

### ISSUE THREAD

**Issue by 1738493726492** [APDevTeam/Movecraft#458]
when i click on a vehicle sign it spams this message in the console: [Movecraft] Task #19 for Movecraft v7.0.0 generated an exception, and the sign does not function. None of them do.

**To Reproduce**
1. Go to your server
2. Click on any vehicle sign
3.  See your console get spammed

**Expected behavior**
I expected Movecraft to work.

 - Movecraft 7.0.0
 - Java Version 8 update 301
 - Minecraft 1.12.2
*Screenshots*
![2021-10-22](https://user-images.githubusercontent.com/93006532/138504092-f37f45b2-3126-471a-a04e-e598b201d950.png)
\

**Comment by TylerS1066** [comment]
Can you expand on which server software you are running?  I've been running 7.0.0 on my servers with no problems for well over a year now without any problems.

**Comment by TylerS1066** [comment]
Since I can not reproduce this, I am closing this.  If you bring more information we can re-open and look into this issue.
