### ISSUE TITLE
1.7.10 support?

### ISSUE THREAD

**Issue by ThatPolishKid99** [APDevTeam/Movecraft#46]
Hi there! 
Thank you very much for continuing the great legacy of this plugin!
I do have one question, namely what is in the title, is 1.7.10 supported? because currently, the latest release version currently does not load properly.
For the record, I am using the Thermos server platform, a Forge/Bukkit merger server

**Comment by cccm5** [comment]
I can look into it but there's no guarantee, 1.7.10->future had some breaking changes in the spigot api

**Comment by ThatPolishKid99** [comment]
That is all i can ask for, thank you!
