### ISSUE TITLE
Kelp prevents subairships from moving

### ISSUE THREAD

**Issue by Pocketkid2** [APDevTeam/Movecraft#469]
On the latest version of Movecraft with Paper 1.18, subairships can't move through kelp. This is not quite so much an error-producing bug as a game-breaking issue as it makes subairships virtually useless because of how much kelp generates in oceans.

**Comment by TheHappyHopper** [comment]
Have you added the passthroughblocks on those craft type files? Done by adding this to your craft file.
passthroughBlocks:
    - kelp_plant
    - seagrass
    - kelp
    - tall_seagrass
    - bubble_column

**Comment by Pocketkid2** [comment]
I remember that option existing, but since I couldn't find it anywhere in the config files I was worried it had been baked into the code somewhere. This particular configuration really should be added to the default BigSubAirship and SubAirship craft files that are in the plugin.
