### ISSUE TITLE
Rmove not working

### ISSUE THREAD

**Issue by GryffindorPlayz** [APDevTeam/Movecraft#473]
**Describe the bug**
Adding the Rmove functionality in the .craft type (maxStaticMove and canStaticMove) does not let me still Rmove

**To Reproduce**
1. Edit the config and add those tags
2. Go back ingame and make an Rmove sign
3. Press it
4. Doesn't move the ship

**Expected behavior**
For the ship to move in that specific direction by how many blocks I set it to move.

**Versions:**
 - Movecraft: 7.0.0.2
 - Java: 17
 - Minecraft 1.17.1

**Additional context**

**Comment by TylerS1066** [comment]
This repository does not have a 7.0.0.2 version.  I believe you are looking for eirik's fork.
