### ISSUE TITLE
Vehicle Permit

### ISSUE THREAD

**Issue by Birddraagon** [APDevTeam/Movecraft#474]
I installed the plugin on the server, when people on the server try to sit down at the technique, they write that there are not enough rights, how can I fix it?

**Comment by TylerS1066** [comment]
If you mean that the players lack permissions to use Movecraft, see our wiki page on it [here](https://github.com/APDevTeam/Movecraft/wiki/Permissions).  You'll need to use whatever permissions plugin you have to allow players to use their crafts by granting them those permissions.

If that's not the problem, I'm afraid I don't understand your issue and I'll need more information.
