### ISSUE TITLE
 Permissions

### ISSUE THREAD

**Issue by Birddraagon** [APDevTeam/Movecraft#475]
I read the page on the wiki, but I did not understand how to give permissions to the player, Can someone explain How do I grant permission to a player?

**Comment by TylerS1066** [comment]
You'll need to install and use a permissions plugin.  I personally use and recommend [LuckPerms](https://luckperms.net/).  Their site has documentation on how to install and use it.

**Comment by Birddraagon** [comment]
Thanks a lot!
