### ISSUE TITLE
Torpedos blow up your own craft

### ISSUE THREAD

**Issue by minerboy101** [APDevTeam/Movecraft#476]
**Describe the bug**
When firing torpedos on 1.18 they will fire and do damage to what ever you hit but they also destroy your ship

**To Reproduce**
1.Make a torpedo and fire it

**Expected behavior**
For it to work

**Screenshots**

**Versions (please complete the following information):**
 - Movecraft: Latest 1.18

**Comment by minerboy101** [comment]
also ive found it works sometimes but when you look at your own craft it then blows up

**Comment by TylerS1066** [comment]
Do you mean that it sinks your main craft or the torpedo?  Can you include some more details on the craft you are using to launch the torpedo and the config options for the torpedo craft?

I was able to successfully use a torpedo on alpha 5 on my 1.17.1 testing server with no problems of the main craft sinking.

Also please include the specific Movecraft version, and addon versions, and Minecraft version (including server software and rev, ex: paper-1.18.1-77).

**Comment by minerboy101** [comment]
on airskiffs it seems to sink my craft and blow it up. but on some crafts it fires and dissapears. im on the latest version of java and spigot

**Comment by minerboy101** [comment]
The toredo fires and hits its target fine. then the craft promptly falls out of the sky giving us the message "your ship has taken damage"

**Comment by minerboy101** [comment]
They also seem to disapear sometimes and not blow up on airships and airskiffs

**Comment by TylerS1066** [comment]
I need the following information to help debug the problem.

What specific Minecraft software and version are you using?  Ex: paper-1.18.1-77
What specific Movecraft version are you using?  Ex: 8.0.0-alpha.5
Do you have any addons installed (such as Movecraft-Combat or Movecraft-WorldGuard)?  If so, please include specific version numbers.
Are you using the default `Airskiff.craft` type file?  If not, please try using it.
Are you using the default `LaunchTorpedo.craft` type file?  If not, please try using it.
What is the block makeup of the skiff you are using?  Ex: 80 blocks total, 51 blocks wool, 1 furnace, 3 signs, etc.
Does the Airskiff fall out of the sky?
Does the torpedo fall out of the sky?
What size torpedo are you using?

**Comment by minerboy101** [comment]
the block make up doesnt matter. all crafts seem not to work. the torpedos vanish. as i said im on the very latest verison of movecraft and spigot. and minecraft.

**Comment by TylerS1066** [comment]
I don't know what to do here.  Torpedoes work on my test server.

I've tried asking you for details on your setup so I can see if there are any differences that may affect the behavior, but you refuse to give me any useful or specific information.

Please answer all my questions directly and specifically, or I will be unable to help you.  For example, I need to know exactly what version of your server software and Movecraft you are running to try and figure out if it's a difference between what I am running and what you are running or a problem in both.

**Comment by minerboy101** [comment]
Okay. im on java 17. minecraft 1.18. 
Im on spigot 1.18.  version 3363-Spigot-f65de01-e36f759 
Movecraft 8.0.0 alpha 5 is the plugin.  
Airskiffs sometimes fall out of the sky.
Most of the time the torpedo will just disapear after launching no matter the craft type or construction. 
this applys to all size torpedos. 
on the rare chance torpedos work they work fine.

**Comment by Rogue197721** [comment]
it is same with me
java 17
paper 388
Movecraft 8.0.0-a.5 by [cccm5, BaccaYarro, TylerS1066, eirik1996, drfiveminusmint, HumorousFool]
random fall of any craft
when firing a torpedo
the error i get is 
[01:24:04 INFO]: [Movecraft] Player Rogue1977 piloted a craft of type LaunchTorpedo with size 7 at location: 4491 x, 4462 z
[01:24:04 INFO]: [Movecraft] Player Rogue1977 has released a craft of type LaunchTorpedo with size 7 at coordinates : 4491 x , 4462 z
[01:24:04 WARN]: [Movecraft] Attempted to move craft with empty HashHitBox!
[01:24:04 WARN]: [Movecraft] Empty craft released

**Comment by minerboy101** [comment]
i dont seem to get a console warning. the torpedo just vanishes. unless im overlooking the console

**Comment by goodroach** [comment]
This happens on 1.16.5 as well, doesn't seem to be version specific. I get the same error described by Rogue here. Does by any chance did any of you guys get the error when launching multiple torpedos at once? When I launch them one by one (where I wait until one explodes) it works fine but when multiple torpedos are in the air and one hits something, the torpedos still in the air start sinking.

**Comment by TylerS1066** [comment]
As of https://github.com/APDevTeam/Movecraft/commit/215642cdc2f3fa7bf9e1f8c6fb7280e2cc9ce3e5, this is working on my Paper 1.14.4 test server.
