### ISSUE TITLE
Sink on pilot

### ISSUE THREAD

**Issue by Laughingspade** [APDevTeam/Movecraft#482]
**Describe the bug**
When you pilot a craft that is a few blocks underneath the water it will instantly fill with water and then proceed to sink. This has happened to two craft currently that have been at least 4 blocks in the water. 

**To Reproduce**
1. build craft with a few blocks in the water
2. type in the command /pilot craft name
3. Craft will fill with water

**Expected behavior**
Movecraft ship will pilot and keep the inside of the hull free of water, if not the craft will clear the water upon first movement and not sink. 

**Screenshots**

**Versions (please complete the following information):**
 - Movecraft: [8.0.0 prerelease 5]
 - Java 16
 - Minecraft 1.17.1

**Comment by TylerS1066** [comment]
This was fixed in https://github.com/APDevTeam/Movecraft/pull/472.

We are working towards fixing a few more bugs before releasing a new alpha, but if you want you can download the latest dev build [here](https://github.com/APDevTeam/Movecraft/actions/runs/1609048570) which includes the fix.
