### ISSUE TITLE
TeleportUtils fix

### ISSUE THREAD

**Issue by Peter-Crawley** [APDevTeam/Movecraft#487]
The issue specified in [TeleportUtils.java Line 85](https://github.com/APDevTeam/Movecraft/blob/7768f0f493b3a22f0060579ae47e5d890f6a442a/modules/Movecraft/src/main/java/net/countercraft/movecraft/util/TeleportUtils.java#L85) has a solution specified [in a message left on the original forum post where the code originated from](https://www.spigotmc.org/threads/teleport-player-smoothly.317416/page-2#post-4186516).

**Comment by TylerS1066** [comment]
This was fixed in #536.
