### ISSUE TITLE
Block Highlights for obstructions

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#491]
The feature that highlights blocks that are going to merge with your craft is pretty cool. What if we used the same system to highlight obstructing blocks for rotating and moving crafts?

**Comment by TylerS1066** [comment]
This is a great idea!

I took a short look into this and the current block highlight feature is very disjoint and spread across a bunch of various files.  I'm not currently sure if I want to keep the feature in the core of Movecraft and clean it up or break it off into an addon, but either way this is not a quick thing to implement.  Regardless it's on the todo list.

**Comment by PinkiBaron** [comment]
Awesome <3

**Comment by TylerS1066** [comment]
I'm going to merge this issue with #534
