### ISSUE TITLE
Calling getType from a Craft object in a third party plugin causes a NoSuchMethodError

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#492]
**Describe the bug**
When calling the getType() method from a Craft object in a plugin supporting Movecraft 8, it will cause a NoSuchMethod to be thrown when run on the server, despite method existig and accessible through the IDE

**To Reproduce**
1. Make a plugin where getType() is called from a craft object anywhere in the code
2. Run plugin on a server along side Movecraft 8
3. Make plugin execute the code calling getType()
4. Notice it will throw a NoSuchMethodError in console

**Expected behavior**
Calling getType() should not throw an error

**Screenshots**

**Versions (please complete the following information):**
 - Movecraft: 8.0.0 alpha 6
 - Java JDK 17
 - Minecraft 1.18.1

**Additional context**

**Comment by TylerS1066** [comment]
As long as you are compiling and running compatible versions of Movecraft, this doesn't happen.

See [Movecraft-Combat](https://github.com/TylerS1066/Movecraft-Combat/blob/main/src/main/java/net/countercraft/movecraft/combat/features/directors/AADirectors.java) for an example.
