### ISSUE TITLE
Server Crashing Bug?

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#494]
I've come across some bug with move craft that causes the server to crash every time I move my land ship. I haven't got a clue as to the cause.

Me and another player were preparing to duel tanks, thus were moving tanks in the same general area. Server suddenly crashed as I moved my ladyship. Every subsequent time the server auto-rebooted, I would try moving my ship, and the server would crash.

I created a small vtest test craft to see if it was all crafts, but it seems to be JUST MINE! I've also piloted without moving, and the server seems fine. I piloted the other landship aswell, and the server doesn't crash. Only my ship does.

Another piece of information, that may be useful is I'm on a hill near the edge of a floating island? (relevant to landships, not certain if this is relevant to the bug).

Version: One of the more recent builds of movecraft 8 beta, tho I'm not sure which.

**Comment by TylerS1066** [comment]
Can you please give us the crash report & log, along with a specific version of Movecraft you are using?  I'd also prefer you run the alpha 6 rather than a dev build to prevent this problem.

**Comment by goodroach** [comment]
I can give more insight to this since I'm the server owner. There was a certain craft that would just lag the server out so much that it would kick the players out of the server. I believe this to be a sort of a case where a craft was being piloted over a corrupted chunk. We ARE using movecraft alpha 6 though, but I don't think movecraft is the cause of the corrupted chunk.

**Comment by TylerS1066** [comment]
Please check the server logs for errors when this craft was moving, but other than that I'm not sure I can help.

**Comment by PinkiBaron** [comment]
Are you positive its not the cause, because this isn't the first case of landships crashing the server

**Comment by TylerS1066** [comment]
Was this possibly related to #497 ?

**Comment by TylerS1066** [comment]
I am going to assume this is related to #497 until I hear otherwise.
