### ISSUE TITLE
Bed/Loadstone that moves with Airship doesn't update player spawn location

### ISSUE THREAD

**Issue by JLLeitschuh** [APDevTeam/Movecraft#495]
**Is your feature request related to a problem? Please describe.**

Currently, if you have a bed set as your spawn point on a craft, then move that craft, when you attempt to use your spawn point (through death or use of the End Portal), you get the error "You have no home bed or charged respawn point, or it was obstructed"

**Describe the solution you'd like**

When you have a bed on a craft set as your spawn point, you should be able to have your spawn point follow the ship.

**Comment by TylerS1066** [comment]
The [Beaming](https://github.com/APDevTeam/Beaming) addon adds `Crew:` signs which allows you to respawn at the crewbed while piloting the craft, and to set a priority crewbed to spawn at when the craft is not piloted.

I eventually plan on reworking the mechanisms to more closely follow what you describe, but it's currently a lower priority than other fixes.
