### ISSUE TITLE
Torpedo collisions causes Movecraft to freeze

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#496]
When firing torpedo subcrafts from a moving craft, and the moving craft intersects with the torpedo, Movecraft seems to freeze. The server seems completely fine, but all crafts that were once moving stop, nothing can rotate, and all functions of Movecraft seem to completely cease. This happens until the torpedo sinks, and everything resumes.

This also occurs when firing multiple torpedos, even from a standstill. The first torpedo in the set will collide and explode like normal, and every other torpedo mid flight, will freeze, movecraft freezes, and then all the torpedos sink, and everything 
continues.

To replicate these scenarios:
a) fire torpedo and move ship as to collide with the torpedo, or while cruising

b) fire a large volume of torpedos  at once.
   

And I can't provide any server logs, so if you want, ask goodroach :)

**Comment by TylerS1066** [comment]
I'd like to request that you leave bug reporting to server owners who have access to all the pertinent information (version, logs, addons, etc).
