### ISSUE TITLE
Disable Sign and Object Interactions When Holding Pilot Tool

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#499]
**Is your feature request related to a problem? Please describe.**
The problem usually is when maneuvering with the piloting tool, usually the stick, clicking around causes occasional activation of a sign, lever, or button accidentally which can be problematic in a cramped bridge or cockpit.

**Describe the solution you'd like**
Basically disabling interactions with objects like buttons, levers, trapdoors as well as command signs like helm, cruise, ascend, and descend when the piloting tool is held in the hand.

**Comment by TylerS1066** [comment]
I started working on this on the [InteractRewrite branch](https://github.com/APDevTeam/Movecraft/tree/InteractRewrite) but have quickly realized that this is a far more complex problem than I initially thought.

I'll continue working on it, but it may be a while longer than I initially thought.

**Comment by TylerS1066** [comment]
As of https://github.com/APDevTeam/Movecraft/commit/716cb7e797451bb536e77b55983510d89354c853, this has been implemented in Movecraft itself.  Addons may not have been updated yet, so I recommend you post issues on each addon if you encounter them.
