### ISSUE TITLE
Repair errors

### ISSUE THREAD

**Issue by cccm5** [APDevTeam/Movecraft#5]
Repairing a ship can sometimes paste the repair schematic in an incorrect position. Most likely due to errors in the repair recognition code, or the ability to have multiple repair signs of the same state.

**Comment by MrUniverseAP** [comment]
Adding onto this, the repair save state failed but still repair's bug

**Comment by keough99** [comment]
What version is this on?

**Comment by MrUniverseAP** [comment]
1.9.2, I just added it on so cc wouldn't forget.

**Comment by keough99** [comment]
Is it also on 1.11.2?

**Comment by MrUniverseAP** [comment]
Its just a return value error and I belive only on 1.9.2 afaik

**Comment by TylerS1066** [comment]
Here is the log file of a repair (on pre-release 6).

https://gist.github.com/TylerS1066/1d188b40c2c2c6efd4f9d14321ea15d4

**Comment by TylerS1066** [comment]
In addition, repairs don't take ammo from chests or repair with ammo anymore, I am not sure if this is a saving or pasting bug.
