### ISSUE TITLE
Merged Fires Stop Spreading Upon Craft Movement

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#500]
**Describe the bug**
Fires that are part of a craft stop spreading upon being moved. This happens even if fire merging is turned off as fires that spread within a ship that take the place of previously present blocks merge and become part of the craft and stop their spread when it moves.

**To Reproduce**
1. Pilot a craft
2. Ignite a fire inside and/or outside
3. Move the ship a bit
4. Fire stops spreading

**Expected behavior**
The fires continue to spread within the ship even if it moves.

**Screenshots**
I don't have any screenshots at the moment but it should apply to all fires ignited on crafts. 

**Versions (please complete the following information):**
 - Movecraft: [Movecraft] Movecraft 8.0.0-a.5
 - Addons: Movecraft-Combat
 - Java 16 - Open J9
 - Minecraft 1.16.5

**Additional context**

**Comment by TylerS1066** [comment]
This likely is related to moving tile entity ticks not currently working either, which I now realize doesn't have a reported issue either.

**Comment by goodroach** [comment]
I tested this in my private server in 1.16.5 and it seems to work.

**Comment by TylerS1066** [comment]
I have as well, I think both 1.14.4 and 1.16.5 have this functioning.  I'm going to keep this open for 1.18 and (soon) 1.20, since I believe we'll continue the pattern and focus on every other worldhandler.
