### ISSUE TITLE
Configurable FireballPenetration Percent

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#502]
**Is your feature request related to a problem? Please describe.**
The chances for firecharges to break blocks when using EnableFireballPenetration aren't able to be configured.

**Describe the solution you'd like**
It would be nice if we could configure the % chance that the penetration can occur which could be useful for changing how quickly AA can bring down a skiff :D

**Comment by TylerS1066** [comment]
Fireball penetration is not a feature of Movecraft, I believe you mean Movecraft-Combat.
