### ISSUE TITLE
Message symbol problem

### ISSUE THREAD

**Issue by MegalithOffical** [APDevTeam/Movecraft#505]
**Describe the bug**
When i add Turkish symbols (ı, ğ, ö, ç) It writed a weird message 

**To Reproduce**
in movecraftlang_en.properties I translate some texts into turkish and the turkish systems show as weird sembols like "±, Â"

**Screenshots**
(https://cdn.discordapp.com/attachments/911685124091940905/949701868588769371/unknown.png)

**Versions:**
 - Movecraft: 8.0.0 alpha 6
 - Addons: Movecraft-Repair v1.0.0
 - Java 17
 - Minecraft 1.17.1

**Comment by TylerS1066** [comment]
Can you verify that you saved the file with UTF-8 encoding?  If possible, please also run `java -XshowSettings` and verify that `file.encoding = UTF-8`?

**Comment by TylerS1066** [comment]
I was able to replicate the issue using this file from one of the members of our discord:
[movecraftlang_ua.zip](https://github.com/APDevTeam/Movecraft/files/10530002/movecraftlang_ua.zip)
![image](https://user-images.githubusercontent.com/7319776/215334237-cb3310c8-b4ec-489d-ac34-d1568071b201.png)
