### ISSUE TITLE
maxHeightAboveGround property is not functioning

### ISSUE THREAD

**Issue by galacticwarrior9** [APDevTeam/Movecraft#506]
**Describe the bug**
The `maxHeightAboveGround` craft property does not function; the craft moves at heights above `maxHeightAboveGround` blocks above the ground without descending as if the property has not been set.

**To Reproduce**
1. Set `maxHeightAboveGround` to a value.
2. Paste in a flying craft that is more than `maxHeightAboveGround` blocks above ground.
3. Move the craft. The craft will continue flying, without descending.

**Expected behavior**
If the craft is more than `maxHeightAboveGround` blocks above the ground, it will descend by one y-level every time it is moved.

**Versions (please complete the following information):**
 - Movecraft: 8, Alpha 6
 - Java 17
 - Minecraft 1.18.1

**Additional context**
[Line 427](https://github.com/APDevTeam/Movecraft/blob/main/modules/api/src/main/java/net/countercraft/movecraft/craft/type/CraftType.java#L427) of the CraftType class returns whichever is highest of the `MAX_HEIGHT_LIMIT` and world's minimum height level. But `MAX_HEIGHT_LIMIT` can be set to `Integer.MAX_VALUE` because of [Line 416](https://github.com/APDevTeam/Movecraft/blob/main/modules/api/src/main/java/net/countercraft/movecraft/craft/type/CraftType.java#L416), so in that case `Integer.MAX_VALUE` will always be returned for the max height above ground. Is it supposed to use `MAX_HEIGHT_ABOVE_GROUND`?

**Comment by TylerS1066** [comment]
As mentioned, this was fixed in the [latest dev build](https://github.com/APDevTeam/Movecraft/actions/runs/1977058853).  Do note, we've dropped 1.18.1 support (and 1.15.2) in favor of 1.18.2 support.
