### ISSUE TITLE
Sinking water ships created immence lag/crash and then entity tile errors at reboot in water.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#51]
We were testing sinking water based ships on my test server as I mentioned, 3/4 ships being sailed fine, we sunk 2 and then another one, and the server came to a grinding halt almost, when I rebooted I was greeted with this in the console.

```
com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntitySign@690e7662) at -1219,39,545 (STATIONARY_WATER) where there was no entity tile!
```

Full error:

https://gist.github.com/FrozenBeard/e23180ac7571f40acbe811d5b36c54bc

I wasn't able to capture a timings report as it just wasn't responding. 

**Edit:** we Tried it again and again and it seems to be with larger ships, im not sure if its specific to the frames or entities on the ship or what, or if its largish (600+ blocks), but im the timings we get 
Minecraft::Bukkit Scheduler
Movecraft::Task: net.countercraft.movecraft.mapUpdater.MapUpdateManager (interval:1) taking up 8000% of the tick.

![screenshot 2018-06-29 22 10 03](https://user-images.githubusercontent.com/144046/42115028-4ac3f020-7be9-11e8-9da9-f95c196eb6a3.png)

This is the second time it happened.
https://gist.github.com/FrozenBeard/ceff395038318b68d1ca48b68b7ba72e

**Comment by cccm5** [comment]
This has been fixed, it was happening because the craft was checking for the exterior/interior every time it moved while sinking
