### ISSUE TITLE
New permision nodes

### ISSUE THREAD

**Issue by TheSidOffical** [APDevTeam/Movecraft#516]
**Is your feature request related to a problem? Please describe.**
A new permision nodes would be great

**Describe the solution you'd like**
movecraft.move.* > Allows all crafts to move
movecraft.pilot.* > Allows all crafts to pilot
movecraft.rotate.* > Allows all crafts to rotate
movecraft.create.* > idk what should i say that
movecraft.repair.* > Allows all crafts to repair

**Comment by TylerS1066** [comment]
I believe most permissions plugins will allow wildcards of the form `movecraft.*.move`.

**Comment by Coder-TheSid** [comment]
Oh ok i will try and test it
