### ISSUE TITLE
Movecraft Multi-World Portals

### ISSUE THREAD

**Issue by denzerinfinite** [APDevTeam/Movecraft#517]
There was a thread from 2020 where it looks like multi-world support was added, I am using the MyWorlds plugin and portals to move between worlds, but when trying to enter a portal while piloting a craft the craft just freezes and doesn't go through. Any info I'm missing on how to accomplish this or is the feature not in the 1.18 version?

**Comment by TylerS1066** [comment]
The PR you reference (#269) added support to bring crafts through nether portals, no other types of portals.  The author of the PR was also working on [an addon](https://github.com/TrollyLoki/MovecraftMultiworldExtensions) to extend support to other plugins, but I am unaware of the status of it currently.  I'd recommend heading there and contacting the author.
