### ISSUE TITLE
LaunchTorpedo Craft disappearing when fired

### ISSUE THREAD

**Issue by supersquids12** [APDevTeam/Movecraft#518]
**Describe the bug**
When right clicking on a "LaunchTorpedo" sign the craft pilots for a moment and then almost immediately disappears.

**To Reproduce**
1. Create a line or blob of up to 7 coal blocks and place a sign adjacent to it, stating "LaunchTorpedo" on the top line. 
2. Right click the sign.
3. Torpedo disappears after piloting

**Expected behavior**
The torpedo is supposed to fly forward until it either strikes a target, and detonates, or reaches the maximum range.

**Screenshots**

![image](https://user-images.githubusercontent.com/34383703/167303760-d972734c-dad8-45ea-838b-984ac2ac6d9d.png)

![2022-05-08_11 36 44](https://user-images.githubusercontent.com/34383703/167303883-aab6d03b-2dc7-4a1d-84f8-edb6630860fa.png)

**Versions (please complete the following information):**
 - Movecraft: 8.0.0 alpha 7
 - Addons: Movecraft-Combat v2.0.0 Alpha 6 
 - Java SE 17
 - Minecraft 1.18.2

**Additional context**
Here is a text version of the logs I received from firing it.
[11:26:21] [Server thread/INFO]: [Movecraft] Player GabeTrafalgar piloted a craft of type LaunchTorpedo with size 3 at location: 350 x, 103 z
[11:26:21] [Server thread/INFO]: [Movecraft] Player GabeTrafalgar has released a craft of type LaunchTorpedo with size 3 at coordinates : 350 x , 103 z
[11:26:21] [Server thread/WARN]: [Movecraft] Attempted to move craft with empty HashHitBox!
[11:26:21] [Server thread/WARN]: [Movecraft] Empty craft released

**Comment by TylerS1066** [comment]
The cause of this is some sort of unintentional gravity type effect, you can solve this by setting the minHeightLimit and maxHeightLimit to the world limits (-64 & 319 respectively).

I've confirmed this behavior on 1.14.4 paper, 1.16.5 paper and 1.18.2 paper.  I'm still determining if this is intended or not.  If it is intended, I'll update the default types.

**Comment by TylerS1066** [comment]
After thinking on this, this is intended such that aerial torpedo type crafts are feasible (launched from above, drops down to say y60, then cruise just below the waterline).

I'll update the default type to be similar to the Airship Pirates `LaunchTorpedo` behavior when launched.
