### ISSUE TITLE
Regarding Block Name Formatting in .craft Files

### ISSUE THREAD

**Issue by TDLF8** [APDevTeam/Movecraft#522]
Switching from Movecraft 7 to Movecraft 8 to run on a 1.18.2 server.

The format of craft files was changed from the "all_[block type] format to the "#[block type]" format. I don't fully understand the conventions of it, and am having difficulty converting old craft files to work with the new version. 

I don't know, for example, if it is "#terracottas" or "#terracota", and it is far to tedious to go in and check the format of every single variation of every single block that is used in the craft file. Is there an easier way to do this? Is there a list of blocks and how to format them? A conversion tool?

**Comment by galacticwarrior9** [comment]
Wasn't the `all_` material prefix a feature of eirikh's fork, not this version?

Regardless, the way I converted from the `all_` format to using the new tags was by simply using the "Replace in Files" feature of Notepad++, which is a free program.

**Comment by TDLF8** [comment]
Perfect. Exactly what I needed, thank you.
