### ISSUE TITLE
Cruise deosn't work

### ISSUE THREAD

**Issue by JXSnack** [APDevTeam/Movecraft#523]
Even though i pressed on the cruise sign, and it turns to "Cruise: ON", the boat deosn't work. I'm using 8.0.0 a7, Minecraft 1.18.2

**Comment by goodroach** [comment]
Can I see your craftfile for this "boat"?

**Comment by DaarkKarma** [comment]
This issue is also present with the default, unchanged, craftfiles.

**Comment by goodroach** [comment]
This is present for 1.18.2 as well Karma? Or is this on a different version? I run a 1.16.5 server and presently face no issues regarding this.

**Comment by DaarkKarma** [comment]
My experience is also on 8.0.0 a7 and tested on 1.18.2.

**Comment by JXSnack** [comment]
Works fine now somehow
