### ISSUE TITLE
/scuttle or sinking a ship leaves frames in the air.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#53]
if you have frames on your ship and /scuttle or sink the water ship, it will just leave the frames where they were in mid-air and not go down with the ship.

![2018-06-29_20 55 44](https://user-images.githubusercontent.com/144046/42112198-00c1a8aa-7bdf-11e8-8363-e51c170ab278.png)

**Comment by cccm5** [comment]
Ya sinking crafts don't take entitys with them, I'll make this configurable to prevent this.

**Comment by cccm5** [comment]
Would not teleporting players, but teleporting all other entities be an acceptable solution to this? Players aren't teleported with sinking crafts to allow them to escape.

**Comment by cccm5** [comment]
Fixed in aeccc13e5ae813fd8cf5be2c3989651c63104322
