### ISSUE TITLE
Default Craft Type Files Allowed Material Entries Not Valid in 1.16.5

### ISSUE THREAD

**Issue by zebotc** [APDevTeam/Movecraft#530]
**Describe the bug**

In Minecraft version 1.16.5 with Alpha Release 7 of Movecraft 8, the default craft files seem to throw errors on server start. The server says something similar to specific material entries in the craft files being invalid material types. 

[Server thread/ERROR] [net.countercraft.movecraft.Movecraft/]: [Movecraft] ERROR PARSING CRAFT FILE: 'BigAirship.craft' Entry #terracotta describes an empty or non-existent Tag for key allowedBlocks

For example the line -"#glass" doesn't seem to work and makes the entire craft file invalid as a craft type. In order to fix this you have to go through the entire craft file system one by one and edit all of the broken entries. But this becomes problematic because my assumption is that #glass refers to all glass types, but in order to fix it you would have to manually enter each glass type one by one. 

Most of the default craft files seem to have this issue, except simple ones.

**To Reproduce**
1. Load Movecraft Version 8 alpha 7 on a 1.16.5 server
2. Look in the server log to see where it has the error about craft files and material types
3. try making one of the invalid files types in game, and it won't work

**Expected behavior**
The expected behavior would be for the craft files to load properly without error.

**Versions (please complete the following information):**
 - Movecraft: 8.0.0 alpha 7
 - Addons: none
 - Java 17
 - Minecraft 1.16.5

**Comment by TylerS1066** [comment]
Please read the FAQ section on getting the datapack to load: https://github.com/APDevTeam/Movecraft/wiki/Frequently-Asked-Questions#800-alphas-wont-load

Unfortunately, the Spigot API does not have much support for datapacks, and for Movecraft to be usable we need to supplement the vanilla tags with our own.
