### ISSUE TITLE
Don't allow players to place blocks.

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#532]
**The full feature:**
The movecraft plugin should have a togglable option that would make it so players cannot place blocks aka any MATERIAL type on your ship at all. This should maybe extend to entities, but this could just be blocks for now. 

**The Solution:**
This would be done by the movecraft hitbox checking for any blocks that get placed inside that ship and cancelling a blockPlaceEvent. This would also cancel any nonconventional methods of placement such as buckets, bonemeal, etc.

**Comment by TylerS1066** [comment]
It should be possible for the pilot of the craft to place blocks on their own craft for in-combat repairs.

**Comment by eirikh1996** [comment]
Would this also include blocks that was placed next to the hitbox too?
