### ISSUE TITLE
No message for /cruise off

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#54]
There is no message for /cruise off when you are cruising.

**Comment by cccm5** [comment]
I've opted to make changing the cruising status of a ship appear as action bar notification for the player. You can see an example here.
![image](https://user-images.githubusercontent.com/15641603/43752208-234e8b42-99ce-11e8-97d4-de861b276a77.png)

**Comment by FrozenBeard** [comment]
I actually requested this about 3 years ago haha, I also requested the action bar to be able to:

- Display damage to the ship/its health
- Display fuel
- Display Direction you are going
- Display speed
- Display how many people are on board
- Display is you are in cruise

We could adapt and add more, just a few ideas.

**Comment by cccm5** [comment]
I'm trying to limit action bar usage to changes in state, so displaying the cardinal direction on turns might happen, but the others are less likely.
