### ISSUE TITLE
BUBBLE_COLUMN obstructs the path of crafts.

### ISSUE THREAD

**Issue by aaashleyyyy** [APDevTeam/Movecraft#545]
**Describe the bug**
Both a bug and not a bug, I just don't think you made it so the crafts would treat bubble columns as regular water.

**To Reproduce**
Trying to go through a bubble column with a movecraft ship.

**Expected behavior**
Treat bubble columns as regular water

**Versions (please complete the following information):**
 - Movecraft: [e.g. 8.0.0 alpha 6]
 - Addons: none
 - Java17
 - 1.19.2

![javaw_8RzT4vtnDR](https://user-images.githubusercontent.com/83358470/187807103-98535986-f951-466e-bcf4-066c4ce1422a.png)

**Comment by HumorousFool** [comment]
Can't you just add bubble column to passthroughBlocks?
