### ISSUE TITLE
Movecraft 8.0.0 alpha 8: Not moving players correctly.

### ISSUE THREAD

**Issue by Galliut** [APDevTeam/Movecraft#553]
**Description**
Crafts are not properly updating player positions when moving. 

This bug is noticeable when cruising or using a pilot tool, but has slightly different behaviours, depending on which of the two you are doing.

I could be moving the craft with a pilot tool and it will completely ignore me, moving without me. This happens every time I change spots and use the pilot tool again.

**To Reproduce w/Pilot Tool**
1. Pilot a craft (I use watercrafts, primarily.)
2. Equip pilot tool.
3. Move craft with pilot tool.
4. Your position will not update properly + often it will disorient the direction you were facing, forcing you to stare at the ground, or turn 180 degrees and look straight up into the sky.

**To Recreate w/Cruise**
1. Pilot craft.
2. Engage cruise.
3. Each cruise skip, you will be fixed to staring in a certain direction, just like with the pilot tool.

**Expected behavior**
Obviously, this is not acceptable and the player's position should be consistent with where they were before the move.

**Console Error Log**
*See attached...*
[message (2).txt](https://github.com/APDevTeam/Movecraft/files/9683669/message.2.txt)

**Versions:**
 - Movecraft 8.0.0 alpha 8

 - Addons:
   - Movecraft-Cannons
   - Movecraft-Combat
   - Movecraft-CoreProtect
   - Movecraft-Repair
   - Movecraft-Towny
   - Movecraft-Warfare
   - Movecraft-Worldguard
 - Java JRE 18
 - Minecraft Release 1.19.0

**Additional context**
It'd be best to reach me on discord for this, as I don't get notifications from GitHub often: **Galliut#5954**

**Comment by TylerS1066** [comment]
Per the [release notes](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0-a.8) of 8.0.0 Alpha 8, 1.19.1 is the only supported 1.19 version.  While you might be able to hunt for the initial 1.19 builds, you won't get support on them.

I highly recommend updating to 1.19.2 and running the latest alpha release, since that is the most stable Movecraft version (besides 7.0).
