### ISSUE TITLE
Tags such as "#glass" and "#chests" failing parse

### ISSUE THREAD

**Issue by DallinFromEarth** [APDevTeam/Movecraft#559]
**Describe the bug**
Using the default craft files generated by the plugin, everything works the first time you boot up. Then, every subsequent boot up, you receive `ERROR PARSING CRAFT FILE: 'Airskiff.craft': Entry #glass is not a valid tag!` Removing the "#glass" from the craft file just has it move down the list to another tag. This prevents the craft from being a valid craft to use in the game. The problem skips "#planks" and "#logs" for some reason

**Expected behavior**
The tags should be processed to allow all types of glass to be in a craft.

**Versions:**
 - Movecraft: [8.0.0 alpha 9]
 - Addons: [none]
 - Java [JDK 13]
 - Minecraft [e.g. 1.19.2] on Paper Server

**Example craft file (.txt added so I could upload it)**
[Airskiff.craft.txt](https://github.com/APDevTeam/Movecraft/files/10305213/Airskiff.craft.txt)

**Comment by TylerS1066** [comment]
Per our [FAQ page on the Wiki](https://github.com/APDevTeam/Movecraft/wiki/Frequently-Asked-Questions#800-alphas-wont-load):
> If there is an error loading craft types stating that there is no valid tag, verify that the file/movecraft-data.zip datapack is loaded and enabled by running /datapack list. If the datapack does not show up, stop the server, set GeneratedDatapack: false in the plugins/Movecraft/config.yml file, and restart the server. Sometimes it takes a few times to get the datapack to load due to limitations in the Spigot API.

This sounds like your server is deleting the datapack for some reason.  Some of the tags we use (such as `#planks` and `#logs` are provided by vanilla Minecraft, but we needed to supplement them with some of our own via the datapack.
