### ISSUE TITLE
Smoother teleportation while moving

### ISSUE THREAD

**Issue by TitanHammer** [APDevTeam/Movecraft#566]
Hello!
While moving In a vehicle pretty fast vehicle teleportation can be very janky and make it a pain to move around. There is a way to fix though this, but I have not found anyway to do this. In a server called horizonsend.net they were able to modify movecraft to move players super smoothly. I contacted the developer and the code that they use is open source. However, I have no experience with plugin development or anything like that and they were not willing to help me further.

**Comment by TylerS1066** [comment]
The latest releases all include full support for smooth teleportation on every supported Minecraft version.

Please re-submit with the full bug report template filled out if beta 1 does not work like expected.
