### ISSUE TITLE
Anticheat bypass

### ISSUE THREAD

**Issue by demizeu** [APDevTeam/Movecraft#569]
Hello dev team,I am an owner of a minecraft server and I really need to know how to have a working movecraft while using an anticheat too.The players can't move because they are limited by the anticheat system.

**Comment by TylerS1066** [comment]
This sounds like an issue with a badly implemented anti-cheat plugin.  You'll need to contact their developers and ask them to fix their bug, there's nothing we can do here without sacrificing functionality.
