### ISSUE TITLE
Signs not staying attached to ships. they wont move with it

### ISSUE THREAD

**Issue by Nymphophobic** [APDevTeam/Movecraft#570]
**Describe the bug**
Signs on ship are staying where placed instead of moving with ship, airship ect. 

**To Reproduce**
Dont know how to reproduce
**Expected behavior**
Signs to move with ship

**Screenshots**
![image](https://user-images.githubusercontent.com/46806103/222587726-a6c2fb72-ff35-4886-aa73-26be97366c1e.png)

**Versions (please complete the following information):**
 - Movecraft: Most Recent Beta
 - Addons: None
 - Java Most Recent
 - Minecraft 1.19.2

**Additional context**

**Comment by TylerS1066** [comment]
Are there any console errors?  Is this with the default types?  Have you confirmed that `"#signs"` is in the `allowedBlocks` of the craft type?
