### ISSUE TITLE
hoverLimit validator is reversed

### ISSUE THREAD

**Issue by animalCodes** [APDevTeam/Movecraft#571]
**Describe the bug**
When setting hoverLimit to any number greater than 0 the craft file will fail to be parsed with the message `hoverLimit must be greater than or equal to zero`.

After some poking around, I've found that the predicate for it's validator is set to `type -> type.getIntProperty(HOVER_LIMIT) <= 0` when it *should* be `type -> type.getIntProperty(HOVER_LIMIT >= 0` (Greater than or equal to 0, not Less than or equal to 0.)

**To Reproduce**
Set hoverLimit to any number greater than 0.

**Expected behavior**
Expected it to parse without issue, I suppose.

**Versions :**
 - Movecraft: 8.0.0_beta-1
 - Addons: None
 - Java OpenJDK 17.0.6
 - Minecraft 1.19.3

**Comment by TylerS1066** [comment]
Good catch, thanks for the in-depth analysis as well!  This should be fixed in the latest dev builds.
