### ISSUE TITLE
Config Option to Disable Incompatible NMS Version Checks

### ISSUE THREAD

**Issue by egundersen** [APDevTeam/Movecraft#584]
The "geniuses" over at Mohist (Hybrid Server Mods/Plugins) had the brilliant idea to use custom NMS Versions. AKA: 1.16.5.LFDSK
Unfortunately, since Alpha 8, Movecraft no longer loads incompatible versions (even though they are compatible).

**Solution**
Add a config option to disable the NMS Version check in IWorldHandler.java
This will fix Mohist Support.

**Comment by TylerS1066** [comment]
This is a really good idea!  I'm thinking that we make it a hidden option in `config.yml` like "IReallyKnowWhatIAmDoing: true`.

**Comment by TylerS1066** [comment]
@egundersen Please try out this dev build, it should have the above mentioned option available to override the version check while still printing a warning:
https://github.com/APDevTeam/Movecraft/actions/runs/5101212802

**Comment by egundersen** [comment]
I will, thanks

**Comment by egundersen** [comment]
Tested it. Seems to work just fine: was able to load using 'IReallyKnowWhatIAmDoing' true. I assume the InvocationTargetException still printed in the console is a caught exception and can probably be ignored?

NOTE: There's a task #3 exception when attempting to move a craft, but I assume that is **unrelated** - probably caused by one of the many changes moving from [alpha 0.0.8] to [beta 1] - and will probably be fixed by Mohist on their end.

**Comment by TylerS1066** [comment]
> the InvocationTargetException still printed in the console

Uh nope, that means that Mohist has a different NMS that is not compatible and is throwing an exception.  If it was an `IllegalStateException` then that would be due to the mechanism used to notify of an incompatible NMS version.  This is further corroborated by the exception when trying to move a craft.  With that said, I think this is as far as we are going to go to add support for modded platforms at this time.

**Comment by TylerS1066** [comment]
As an aside to developers who stumble upon this and decide they would like to add support for an unsupported version that only lacks a worldhandler, you should be able to create the proper classes at `net.countercraft.movecraft.compat.<version>.IWorldHandler` (or revive them from removed versions).  Again, we aren't going to provide support to server owners running anything other than the officially supported versions, worldhandlers and server platforms, but we aren't going to stop you.  There isn't a way to replace an officially supported worldhandler with a custom one, but I don't foresee a need to.
