### ISSUE TITLE
Incendiary toggle for ExplosionEvent  

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#586]
**Is your feature request related to a problem? Please describe.**
I want torpedos and other collision-explosion craft to do some fire damage along with their typical explosion. 

**Describe the solution you'd like**
This is quite simple iirc, as all I need to do is to add a new craft config setting, add a boolean that toggles incendiary effect in ExplosionEvent, and finally add a boolean parameter to the createExplosion() method to allow for an incendiary effect.

**Comment by TylerS1066** [comment]
Is there a parameter for the amount of fire to use?  If so, we should also include that, but I like the idea.

**Comment by goodroach** [comment]
No, unfortunately, it's just a boolean in the createExplosion method. I personally don't think it matters that much but I can just add this feature if you like. Do you have any recommendations on my particular solution?

**Comment by TylerS1066** [comment]
That should cover it, my one note is to make sure that the incendiary flag is passed to the event so protection addons can work with it.

**Comment by TylerS1066** [comment]
Closed in #677
