### ISSUE TITLE
Turning water ships when static can leave giant holes in water.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#59]
I was testing the latest build with a 4500 sea ship, I stopped cruise as I saw land approaching and turned the ship twice. this left 2 giant ship shaped holes in the sea.

![2018-08-08_14 39 13](https://user-images.githubusercontent.com/144046/43840678-224722da-9b19-11e8-8270-d8ed953d1001.png)

**Comment by cccm5** [comment]
Hmm thats strange, You're testing this on 1.12 correct?

**Comment by cccm5** [comment]
Fixed!
