### ISSUE TITLE
Cruise on Pilot Configurable Max Flight Time & Collision Explosion Minimum Range

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#594]
**Is your feature request related to a problem? Please describe.**
Something I think would be good would be more customizability to torpedoes in terms of preferred engagement distances. A torpedo type that could be made is a really fast type. But the issue lies in that introducing a fast torpedo means that firing at very close ranges would make it unavoidable. The ability to configure the minimum range of a torpedo before the collision explosion is enabled would give the ability to prevent torpedo rams or skiffs moving way too close to fire. 

Another relates to slow, large, and heavy torpedo types. The current system means that slow torpedoes travel only very short distances since range correlates to speed because of the fixed flight time. Having the ability to configure flight time allows for the creation of long range slow and heavy torpedoes.

**Describe the solution you'd like**
Two additional settings to the craft file that would kind of be like:
collisionExplosionArmingTime: 
cruiseOnPilotMaxFlightTime:

**Comment by goodroach** [comment]
This is a duplicate. There's an older issue #420 that asks for specifically this.

**Comment by MysteryTimeTrav** [comment]
> This is a duplicate. There's an older issue #420 that asks for specifically this.

o

Should I separate this to just a configurable arming time/minimum range suggestion and remove the flight time part?

**Comment by goodroach** [comment]
Yeah, I think that would make more sense. I think the arming distance should be a thing as well. Though the configuration method might be a bit difficult to implement as it's a conditional setting that relies on CruiseOnPilot and CollisionExplosion to be true.

**Comment by TylerS1066** [comment]
Let's expand upon #420 rather than open another issue, since these are both essentially the same thing.
