### ISSUE TITLE
Camera Issue When Moving in 1.19+

### ISSUE THREAD

**Issue by MysteryTimeTrav** [APDevTeam/Movecraft#596]
**Describe the bug**
Occasionally when moving a craft in any way (cruise and manual stick), the player camera will snap to facing directly straight up or straight down. It can easily be observed in fast moving crafts or using the manual stick to maneuver since because it seems to be a random chance and moving more times means it occurs more often.

**To Reproduce**
1. Load in 1.19+
2. Pilot a craft and start moving around a bit
3. Camera will occasionally snap up or down

**Expected behavior**
Camera movement to be smooth and remain where you were originally facing at all times

**Screenshots**
If applicable, add screenshots (or videos) to help explain your problem.

**Versions (please complete the following information):**
 - Movecraft 8.0.0_beta-1
 - Addons (latest): Movecraft-Combat, Movecraft-Cannons, Movecraft-WorldGuard, SquadronsReloaded
 - Java 19
 - Minecraft 1.19.3

**Additional context**

**Comment by TylerS1066** [comment]
Interesting, I was under the assumption that smooth teleportation worked on 1.19.3.  Can you try the [latest dev build](https://github.com/APDevTeam/Movecraft/actions/runs/5230540339) on 1.19.4 and let me know how it goes?
