### ISSUE TITLE
Sinking is broken

### ISSUE THREAD

**Issue by chapinalc** [APDevTeam/Movecraft#598]
**Describe the bug**
When an airship should sink (due to wool burning), it instead just releases the craft. The only relevant message in console is:
[17:38:44] [Server thread/INFO]: [Movecraft] NULL Player has released a craft of type Airship with size 1674 at coordinates : 19955 x , 192 z

**To Reproduce**
Make an airship, pilot it, then burn the wool until it should sink. Use a regular superflat world with ground at around y=-60, so you can fly the ship at roughly y=-40.

**Expected behavior**
The airship should sink to the ground.

**Versions (please complete the following information):**
 - Movecraft 8.0.0 beta 2
 - Java 18
 - Minecraft: Spigot 1.18.2

**Comment by goodroach** [comment]
At what Y coordinate does this happen? Crafts don't sink below past a certain height iirc.
