### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheZenKitteh** [APDevTeam/Movecraft#6]
Followed your instructions below, craft doesn't move.

EDIT: The pilot tool doesn't work. I've tried a few different pilot tools and none work. I can use commands to make the craft rotate and cruise but I can't go up or down or control it in any other way. Also is there a command to reload the plugin in game because it's a pain to restart the server every time I need to try some different config, especially when other players are on.

This are quick and dirty instructions to rapidly get up and flying in Movecraft. We won't be covering permissions, or customization, or any of the other advanced features. For that, read the other materials on this website, or watch the longer tutorial.

    Obtain a fresh install of Craftbukkit or Spigiot. Run it once in order to create the directory structures we will be using.
    Download the newest version of Movecraft from this page and extract the .jar from the .zip and place it in your \plugins directory.
    Start Craftbukkit again so it will create the Movecraft directory structure we will need.
    Download the craft files: https://dl.dropboxusercontent.com/u/11164014/MovecraftTypes.zip and extract the .craft files from within the .zip into your plugins\Movecraft\types directory. - THIS IS COMMONLY MISSED
    Give yourself server OP permissions by typing: "op YOURNAMEHERE" in the server console. NOTE: this gives full rights to any user you specify here. It is a quick way to get Movecraft working, but it is highly recommended you set up rights more granularly for your users. See the tutorial for more details.
    Start your server one last time.
    Open your Minecraft client and connect to your server.
    In the game, find a spot that is on dirt or grass that is not near any trees or water. Place a redstone block on the ground. (This represents the ships engines)
    Place any color of wool blocks in a square around the redstone block. You will need 8 wool blocks to complete the square around the redstone block.
    Replace one of the wool blocks with a furnace. It doesn't matter which one.
    Put some coal, charcoal, or coal blocks into the furnace. This if your fuel.
    Place a sign on top of one of the wool blocks. The first line of the sign must say only "Airskiff" (without quotes). The other lines can say anything you want. It is customary to name the craft, so you may add a name to the sign after the first line.
    With a stick in your hands, right click on the sign you created. You should get a message saying "Successfully piloted craft!".
    Now right click with the stick still in your hands in the direction you want the craft to go. You should be able to move in any direction as long as you are not blocked.
    Now play around with the more advanced features. Maybe add a sign that says [helm] and right click it to turn it into a control wheel. Left and right click that sign with an empty hand to turn the ship. Maybe play around with more advanced features, like cruise control and fuel consumption. Customize your .craft file to make your dream machine.
    Have fun! 

1.12.1 spigot

**Comment by TheZenKitteh** [comment]
Well, another player and I have been messing with it, still can't control the craft but the other player started getting spammed with stuff and the console log blew up to over 5MB quickly. The error only stopped after she disconnected and reconnected.

It spammed this error over and over
https://pastebin.com/raw/WYJHrW7m

**Comment by cccm5** [comment]
This is not the official movecraft repo (yet), but based on that log you're using movecraft 4 on 1.12.1. I would recommend trying the version available on spigot released on November 8th 2016. The more recent updates will also fail to work on 1.12, so make sure to get the correct version. You'll also need a copy of world guard and world edit in your plugin folder due to a bug.

**Comment by keough99** [comment]
the version that would work on 1.12.1 is https://www.spigotmc.org/resources/movecraft.31321/update?update=124592
but like cccm5 said you will need to install world guard and world edit along with it.

**Comment by TheZenKitteh** [comment]
cccm5, I downloaded the version in the summary for this project as the latest movecraft on spigot didn't work, but you knew this already lol. I just downloaded and installed the version specified and the pilot tool still doesn't work. All it can do is let you begin piloting the airship but you can't control it. The only way I've been able to control it is with signs which is very cumbersome.

**Comment by keough99** [comment]
currently movecraft only supports 1.8 i have a fork that adds basic support for 1.11.2 but its not fully done as its base is this repository

**Comment by cccm5** [comment]
Ya the repository readme has yet to be updated, I'm gonna close this since it seems you've sorted it out
