### ISSUE TITLE
Paintings keep coming off

### ISSUE THREAD

**Issue by JamjamSA** [APDevTeam/Movecraft#601]
I'm using a ship that has paintings on it. Basically, when I move my ship forward, every painting stays in place. However, whenever I use the helm and rotate the ship, all of the paintings stay the way they were before the ship turned and they come right off. Is there an option in the .craft file that I should know about that stops this issue?

**Comment by goodroach** [comment]
Paintings are not a block, but an entity. They will not merge to your craft nor will be moved by them. This won't move armor stands for the same reason.

**Comment by Thenolypus** [comment]
Hi :) I replied to your Q&A in the discussion section. Do check it out and let me know if it had helped you. What would also be useful information of this incident from your side is to provide the Minecraft version you were using, which Movecraft version you were using and along with what server you were using (Spigot? Paper? Only relevant if you are hosting a Minecraft server).
