### ISSUE TITLE
Craft is obstructed by nothing...

### ISSUE THREAD

**Issue by K3rn31pan1c** [APDevTeam/Movecraft#604]
![Screenshot from 2023-07-18 12-32-22](https://github.com/APDevTeam/Movecraft/assets/81191426/cf4c5fb1-5903-4646-bdbb-b06c073267ee)
![Screenshot from 2023-07-18 12-32-54](https://github.com/APDevTeam/Movecraft/assets/81191426/4f8ca15e-d99d-4667-964e-f4e7a5ed73bf)
When trying to move an airship, console claims obstruction and nothing is there but air...

**To Reproduce**
1. Build airship
2. Click helm
3. "Craft is obstructed @ xyz" but nothing is there except air

**Expected behavior**
To go lol

**Screenshots**
If applicable, add screenshots (or videos) to help explain your problem.

**Versions (please complete the following information):**
 - Movecraft_8.0.0-beta-2
 - Addons: None
 - openjdk 17.0.7 
 - Minecraft 1.20.1

Just dont understand what it thinks it sees. Second image is above the cords it gave looking down to show nothing there.

**Comment by goodroach** [comment]
If you look at the craft is obstructed sign, you will notice that it will tell you where it's obstructed. Maybe see is that block is an air block? What I think is happening is that your ship doesn't have that block added to the craft type file.

**Comment by K3rn31pan1c** [comment]
If i add air blocks to the list it thinks all the air is part of the ship. Is everybody else adding air to their craft type?

**Comment by K3rn31pan1c** [comment]
> If you look at the craft is obstructed sign, you will notice that it will tell you where it's obstructed. Maybe see is that block is an air block? What I think is happening is that your ship doesn't have that block added to the craft type file.

If i add air blocks to the list it thinks all the air is part of the ship. Is everybody else adding air to their craft type?

**Comment by TylerS1066** [comment]
No, what goodroach meant was to look at the coordinates and see what is obstructing you.
