### ISSUE TITLE
bring back remote control for aircrafts

### ISSUE THREAD

**Issue by ShyneeKaufman** [APDevTeam/Movecraft#625]
If i remember at old versions(for 1.12) was feature which allowed to make remote control all craft from ground
can it be bringed back?

**Comment by TylerS1066** [comment]
I don't remember this ever being a feature of Movecraft itself (nor has it been removed).  Perhaps you are referring to the never maintained add-on [Squadron Directors](https://github.com/Baccayarro/SquadronDirector)?
