### ISSUE TITLE
DismantleElevator not working on single chests that are side by side

### ISSUE THREAD

**Issue by lukeocvirk** [APDevTeam/Movecraft#630]
**Describe the bug**
When using DismantleElevator type craft it will get stuck on single chests that are connected side by side despite not being double chests and despite being one of the blocks allowed to be dismantled by the craft type.

**To Reproduce**
1. Try to dismantle through chests that are connected on the same plain that the craft is dismantling through.
2. It seems this is not always an issue and is only an issue in certain configurations, in this case all the chests facing the exact same way.

**Expected behavior**
It should dismantle right through the chests but it seems that it may be mistaking these singular chests side by side for double chests. If I were to guess it could be that crafts that use singular chests side by side are blocked whereas ships with a mix of regular chests and trapped chests are accepted.

**Screenshots**
Screenshot 1 shows how the ship is being prevented at the height in which all the chests are present.
![ver1](https://github.com/APDevTeam/Movecraft/assets/161389297/1ab2f504-6d57-4ef1-9351-b35628178659)
Screenshot 2 shows how I had to separate the chests in order for the craft to dismantle it properly.
![ver2](https://github.com/APDevTeam/Movecraft/assets/161389297/00453a07-b8d5-40a3-92d3-f26474ecb198)

**Versions (please complete the following information):**
 - Airship Pirates SS configuration (1.16)

**Comment by TylerS1066** [comment]
To clarify, we are running a dev build from aa33964aea62eb7005df6a39adac1d098bfb13ae.
