### ISSUE TITLE
Lag out of ships if not big enough/ direct control mode

### ISSUE THREAD

**Issue by Moose141414** [APDevTeam/Movecraft#634]
when ever i click to move i lag out of the ship and fall and idk how to keep that form happing but i just made the ship bigger so it wouldn't happen but i still want to see it get fixed and direct control mode will not work at all all that works is going down and up if  someone could help thanks, I'm also using 1.19.4 version of Minecraft.

**Comment by TylerS1066** [comment]
Unable to replicate.  Please reopen this issue and fully fill out the bug report template, including the server platform and build umber.
