### ISSUE TITLE
Movecraft ship doesn't go any higher 

### ISSUE THREAD

**Issue by YETIMAN2020** [APDevTeam/Movecraft#636]
**Describe the bug**
Airship/Airskiff wont go any higher than y103
this is using other plugins and world gen data pack
note changing the max height config has no effect 

**To Reproduce**
im not sure other than installing the same data packs
![movecraft data packs](https://github.com/APDevTeam/Movecraft/assets/64026995/91a3b23f-a04d-4ac9-93e4-6d873cb2410f)

**Expected behavior**
airship/airskiff moves up then back down a block

**Versions (please complete the following information):**
 - Movecraft: 8.0.0-beta-2
 - Addons: Movecraft-coreprotect_1.0.0_beta-1, Movecraft-Repair Dev build
 - Minecraft 1.20.1 paper

**Comment by TylerS1066** [comment]
The default types have a `maxHeightAboveGround` which is a soft "altitude" limit and acts like you mention.  The `maxHeightLimit` is a hard limit which will give the player a warning if they try to go above it.

**Comment by YETIMAN2020** [comment]
i tried reinstalling movecraft completely and it now works, its a little confusing but atleast its working now
