### ISSUE TITLE
Is there a way to get persistent block data on non tile entities?

### ISSUE THREAD

**Issue by ddowen** [APDevTeam/Movecraft#638]
I have this special block that has a special block data nbt tag, but it becomes a normal block when moving, any fix?

**Comment by TylerS1066** [comment]
I thought that NBT data for blocks was part of the `BlockState`, in which case it should be moved with it?  If not, we'd need to do an analysis of the performance impact of moving NBT data.

**Comment by TylerS1066** [comment]
With the merging of #673, I am certain that `PersistentDataContainer`s are moved with crafts.
