### ISSUE TITLE
Big Suggestion (too big to fit in a title)

### ISSUE THREAD

**Issue by MulverineX** [APDevTeam/Movecraft#64]
originally posted in the official movecraft spigot forum, and an issue on msummers123's fork, here's the post: https://www.spigotmc.org/threads/movecraft.191041/page-3#post-2308400

**Comment by MulverineX** [comment]
Possibly this could be done in the 1.13 update where major code rewrites would take place.

**Comment by TylerS1066** [comment]
While this would be interesting, I think it's a bit outside the current scope of the project.  If somebody wanted they could implement this in an addon.
