### ISSUE TITLE
Permissions in Craft type files

### ISSUE THREAD

**Issue by Nikkilectric** [APDevTeam/Movecraft#649]
**Is your feature request related to a problem? Please describe.**
Right now, You have to specifically add permissions based on type files which can be an issue for servers who want to use their own permissions

**Describe the solution you'd like**
In craft type files, add the ability to add your own required permission node

**Comment by TylerS1066** [comment]
Changing the permission structure based on the craft file is not an easy change.  In addition, servers only need to learn the structure once and then can forget it.
