### ISSUE TITLE
How do I use movecraft as a dependency?

### ISSUE THREAD

**Issue by Nikkilectric** [APDevTeam/Movecraft#661]
I've tried using both github packages & the instructions in the wiki, Whenever I try to build my plugin I get this error:

![image](https://github.com/APDevTeam/Movecraft/assets/136409902/64d8eec9-10e3-46af-9f62-58e8a50be17b)

It's the same if I use "LATEST" as my version in my pom.xml, How do I properly add Movecraft as a dependency to my Pom.xml file?

Done by using ```mvn clean install -U```

**Comment by TylerS1066** [comment]
[Movecraft-CoreProtect's pom.xml](https://github.com/APDevTeam/Movecraft-CoreProtect/blob/main/pom.xml) is probably the best minimal example of how to construct a Movecraft addon, but our [Wiki Page](https://github.com/APDevTeam/Movecraft/wiki/Documentation) goes into more detail on how to set up your development environment.  You need to do 3 steps:
1. Set up your maven settings to authenticate with GitHub packages
2. Add our GitHub packages repository
3. Add Movecraft as a dependency

Another thing to note, the Movecraft ecosystem is in the progress of transforming from Spigot plugins built via Maven into Paper plugins built via Gradle to take advantage of the [many APIs](https://docs.papermc.io/paper/dev/api), helpful [development features](https://docs.papermc.io/paper/dev/internals), and [more](https://github.com/APDevTeam/Movecraft/pull/662) that Paper provides.  We don't have any documentation or examples of doing this yet, but we'll be busy over the next few weeks converting the many addons.

**Comment by Nikkilectric** [comment]
Thanks!
