### ISSUE TITLE
Add craft methods to get the block amount of a craft

### ISSUE THREAD

**Issue by Intybyte** [APDevTeam/Movecraft#678]
**Describe the solution you'd like**
A way to get informations about the amount of blocks in a craft, for instance:

Block Amount
Move Block Amount
Flyblock Amount

This might be useful for addons, a simple use might be getting the Block Amount on Pilot and then using that amount to calculate the amount of blocks left on the craft, or if there are few moveblocks on the craft while piloting it.

**Comment by TylerS1066** [comment]
> Block Amount
This one already exists: `Craft.getDataTag(Craft.MATERIALS)`.  

The other two would be a good idea, and would be able to combine the `StatusSign` calculation with the official calculations caching their value in `StatusManager`.
