### ISSUE TITLE
Pre release 5 not working

### ISSUE THREAD

**Issue by keough99** [APDevTeam/Movecraft#68]
hello movecraft pre-release 5 is not working on 1.12.2 its spamming console with null pointer exceptions

https://pastebin.com/ESWhr7F2

**Comment by cccm5** [comment]
Could you give me a list of plugins you're using, preferably with their versions

**Comment by keough99** [comment]
heres a list https://pastebin.com/QVskSNYt

**Comment by keough99** [comment]
any status?

**Comment by keough99** [comment]
i have tracked down the issue to my craft files im not sure what the issue is but its something with cruise manager
[types.zip](https://github.com/APDevTeam/Movecraft/files/2660812/types.zip)

**Comment by TylerS1066** [comment]
I believe 1.12 support is still iffy even on pre-release 6, but it is going to be done before the official 7.0 release.
