### ISSUE TITLE
Siege payment broken

### ISSUE THREAD

**Issue by cccm5** [APDevTeam/Movecraft#7]
after paying out to the first player, siege payments cause an npe.

**Comment by TylerS1066** [comment]
Elaboration:

The siege pays a player for 1/3 the money of the city, and this player is added as both a name and uuid owner.  We suspect that it tries to pay the name owners as uuids, and the uuid owners by name

**Comment by TylerS1066** [comment]
I believe this was fixed in https://github.com/APDevTeam/Movecraft/pull/96, but could somebody confirm for me?  Maybe @TheDigitalDev ?

**Comment by TylerS1066** [comment]
I'll be testing this with #121 to see if it is broken or not.
