### ISSUE TITLE
Suggestion: Movecraft as Maven and Gradle repositories

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#70]
As Movecraft 7.0 will come out, developers may be interested in making plugins that add extra functions to Movecraft or will add support for Movecraft. My suggestion is therefore: Host Movecraft as Maven and Gradle repositories.

**Comment by cccm5** [comment]
I've recently been accepted into the [github package registry](https://github.com/features/package-registry) beta, so this is something that will happen sometime soon:tm:.

**Comment by TylerS1066** [comment]
For Movecraft addon developers, please see our updated documentation on how to use Movecraft as a dependency on our wiki: https://github.com/APDevTeam/Movecraft/wiki/Documentation

If you want to see some examples, feel free to look at the [many](https://github.com/TylerS1066/Movecraft-Combat/pull/78) [many](https://github.com/APDevTeam/Movecraft-Warfare/commit/9da5b1308d79261620cf5b4e8ac0b18b3dcda2cb) [many](https://github.com/APDevTeam/Movecraft-Repair/commit/8eda6aead58c4072d327222eacab8c0b2aedae38) [addons](https://github.com/TylerS1066/Movecraft-Towny/commit/621590296ebc4b1c47b6d638d64eeacded5073d1) [that](https://github.com/TylerS1066/Movecraft-Cannons/commit/6cfdb031c00a27fe5141e9a03f8170b26a547934) [we](https://github.com/APDevTeam/Beaming/commit/51c74c088cd4c772a9a9f9d620281be4c222b41f) [maintain](https://github.com/APDevTeam/Ap-Turrets/commit/ece33e31cf168aa54c56e1681374ccd832a2b7ba).
