### ISSUE TITLE
Plugin not started in 1.20.4

### ISSUE THREAD

**Issue by euvoutepossuir** [APDevTeam/Movecraft#709]
The plugin does not start on the server, it says that it does not offer support for version 1.20.4, however in the releases of version 8.0.0 Beta 3 it says that this support exists.
I'm on version 1.20.4 and using jar 21.

Tested versions:
Movecraft 8.0.0 Beta 5
Movecraft 8.0.0 Beta 4
Movecraft 8.0.0_beta-5_dev-1
Movecraft 8.0.0 Beta 3

Error:
![image](https://github.com/user-attachments/assets/9539bd2d-4357-40ad-8bb8-08cdd07ddbae)

**Comment by TylerS1066** [comment]
None of the versions you listed support 1.20.4, as the error states.  I recommend updating to 1.20.6 and running the latest beta or downgrading to 1.20.1 and running beta 2.

You can find the list of supported versions here: https://github.com/APDevTeam/Movecraft/wiki/Frequently-Asked-Questions

**Comment by euvoutepossuir** [comment]
It would be a huge headache to have to change my server version now, are there no solutions to launch movecraft in this version? After all, they said they added version 1.20.4...

![image](https://github.com/user-attachments/assets/e160b826-83a2-485f-82e5-05e24ec96fa7)

@TylerS1066

**Comment by euvoutepossuir** [comment]
You yourself were the one who made this update.

![image](https://github.com/user-attachments/assets/e293f1fd-972e-4a96-ac6c-4e359a17f604)

**Comment by TylerS1066** [comment]
Yes, we upgraded from 1.20.1 to 1.20.2, then 1.20.2 to 1.20.4, then 1.20.4 to 1.20.6 all in the development between beta 2 and 3.  We only support the latest minor Minecraft version for a major Minecraft version at a time.

If you must run 1.20.4, this old dev build should work, but will be lacking the latest features, performance improvements, and bug fixes: https://github.com/APDevTeam/Movecraft/actions/runs/9438979699

**Comment by euvoutepossuir** [comment]
Don't worry, thank you very much!! 5-star support. Is there an estimate of when they will "abandon" version 1.20.6 too?

**Comment by euvoutepossuir** [comment]
I'll try to reproduce it then, then update the topic here.
