### ISSUE TITLE
Anti cheat suggestion

### ISSUE THREAD

**Issue by AkameYatogami** [APDevTeam/Movecraft#714]
I've tried a couple anti cheat plugins now but they all have an issue with Movecraft, the player will be flagged for movement hacks and will not be moved with the craft.

I'm okay with a premium suggestion if it works with Movecraft, but don't want to go blind if it doesn't work.

Has anyone had luck with an anti cheat that works with Movecraft that they could suggest?

**Comment by wolfebersahd** [comment]
Every anticheat plugin works with movecraft. As the dev which setting you should adjust in the anticheat config to not trigger a false positive with movecraft. Usually there are two, a flying setting for not standing on a block briefly before teleport, and second a moved too quickly one.

Most anticheats have threshold options that you can increase to no be triggered by movecraft.
