### ISSUE TITLE
useGravity is not working

### ISSUE THREAD

**Issue by STEngineer** [APDevTeam/Movecraft#75]
**Describe the bug**
useGravity is not working

**To Reproduce**
1. Set useGravity to true
2. Try to translate the craft
3. Craft will not go down

**Expected behavior**
Craft should fall down, but doesn't

**Comment by cccm5** [comment]
gravity is not implemented currently

**Comment by TSEngineer** [comment]
So how do I make a car for now?

**Comment by TSEngineer** [comment]
Did useGravity work earlier?

**Comment by TylerS1066** [comment]
Currently you can not make a car-type craft with 7.0 pre-releases, as they are still pre-releases without the full feature set.  If you wish for the full features (with plenty of lag) you can use 6.0.  The useGravity feature did work in 6.0, but again 7.0 is a major rewrite and as such, some features were dropped in the pre-releases (but will be back before the full release).

**Comment by TSEngineer** [comment]
Also you can just use Movecraft 7.0.0_pre-release_3
https://github.com/APDevTeam/Movecraft/releases/tag/7.0.0_pre-release_3
My Car craft file content:
`name: LandVehicle
maxSize: 500
minSize: 25
allowedBlocks:
  - 5
  - 10
  - 11
  - 17
  - 20
  - 22
  - 23
  - 25
  - 26
  - 29
  - 33
  - 34
  - 35
  - 41
  - 42
  - 43
  - 44
  - 47
  - 50
  - 51
  - 53
  - 54
  - 55
  - 57
  - 58
  - 61
  - 62
  - 63
  - 64
  - 65
  - 68
  - 69
  - 70
  - 71
  - 72
  - 75
  - 76
  - 77
  - 82
  - 85
  - 87
  - 89
  - 92
  - 93
  - 94
  - 95
  - 96
  - 98
  - 101
  - 102
  - 107
  - 109
  - 112
  - 113
  - 114
  - 116
  - 117
  - 118
  - 121
  - 122
  - 123
  - 124
  - 125
  - 126
  - 130
  - 131
  - 133
  - 134
  - 135
  - 136
  - 138
  - 139
  - 140
  - 143
  - 144
  - 145
  - 146
  - 147
  - 148
  - 149
  - 150
  - 151
  - 152
  - 154
  - 155
  - 156
  - 157
  - 158
  - 159
  - 160
  - 162
  - 165
  - 171
  - 172
  - 173
  - 165
  - 167
  - 183
  - 184
  - 185
  - 186
  - 187
  - 188
  - 189
  - 190
  - 191
  - 192
  - 193
  - 194
  - 195
  - 196
  - 197
  - 206

speed: 20.0
allowAADirectorSign: false
allowCannonDirectorSign: false
allowHorizontalMovement: true
allowRemoteSign: true
allowVerticalMovement: true
allowVerticalTakeoffAndLanding: true
blockedByWater: true
canCruise: false
canDirectControl: true
canFly: true
canHover: true
canHoverOverWater: false
canStaticMove: true
canTeleport: false
chestPenalty: 0.0
collisionExplosion: 0.0
cruiseOnPilot: false
cruiseOnPilotVertMove: 0
cruiseSkipBlocks: 0
cruiseSpeed: 0.0
detectionMultiplier: 1.0
dynamicFlyBlock: 0
dynamicFlyBlockSpeedFactor: 0.0
explodeOnCraft: false
flyblocks:
  1:
    - 0.0
    - 100.0
focusedExplosion: false
forbiddenBlocks:
  - 7

forbiddenSignStrings:

fuelBurnRate: 0.1
halfSpeedUnderwater: false
harvestBlocks:
  - 31
  - 30
  - 18
  - 6
  - 32
  - 37
  - 38
  - 39
  - 40
  - 50
  - 81
  - 78
  - 106
  - 111
  - 161
  - 171
  - 175
  - 425
  - 331

harvesterBladeBlocks:

hoverLimit: 0
keepMovingOnSink: false
maxHeightAboveGround: 0
maxHeightLimit: 254
moveEntities: true
overallSinkPercent: 0.0
onlyMovePlayers: true
passthroughBlocks:

requireWaterContact: false
rotateAtMidpoint: true
sinkPercent: 0.0
sinkTickRate: 0
sinkSpeed: 0
smokeOnSink: 0
staticWaterLevel: 0
tryNudge: false
underwaterDetectionMultiplier: 0.0
useGravity: true
vertCruiseSkipBlocks: 0`

**Comment by cccm5** [comment]
I wouldn't recommend using an old pre-release, some had world breaking bugs. Remember, these pre-releases are intended for testing only. I advise against using them in any production enviroment

**Comment by wolfebersahd** [comment]
What's the status on this?

I use UseGravity as a form of controlled buoyancy for large crafts. I set the minimum height to 1, 2, or 3 block(s) below water level, depending on the ship class' size. When piloted, the larger craft automatically sinks to the minimum set height when moved making it slightly more realistic that larger ships have more water displacement. I read in the PR that it would only descend if the block below it is air, that would break my ship types that work in Movecraft 5.

I'm in no particular rush, just curious how this is coming along.

**Comment by cccm5** [comment]
The PR was incorrectly closed, it was never actually merged. It's now currently being worked on by @eirikh1996
