### ISSUE TITLE
Idea: Make motion of non-player entities a configurable option and add ability to disable or edit SiB placement restriction

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#8]
The ability to enable/disable mob movement should be added. In addition, the option to restrict SiB placement to regions should be made configurable.

**Comment by cccm5** [comment]
Sib restriction is already toggle-able under "RestrictSiBsToRegions" in the Movecraft settings.yml. if it doesn't exist, just add it and it should be recognized by Movecraft

**Comment by eirikh1996** [comment]
But is a toggleable option for non-player entity movement under development?

**Comment by cccm5** [comment]
Done
