### ISSUE TITLE
Sinking and ship despawning

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#80]
Crafts can sometimes leave behind air blocks when sinking, or despawn partially.

Examples:
https://imgur.com/oySyl4g
https://cdn.discordapp.com/attachments/530158744793776158/530174452135362580/2019-01-02_16.03.15.png

**Comment by TylerS1066** [comment]
Updates:
This only seems to happen when crafts sink into water, not onto land.

This also was found on 1.10.2

**Comment by eirikh1996** [comment]
Additionally, the console is spammed with warnings looking like this: Attempted to place TileEntity(tileEntityType) at x, y, z (STATIONARY_WATER) where there was no entity tile, followed by a stacktrace when a player joins in or approaches an area where a craft sunk into water

**Comment by cccm5** [comment]
Fixed by #102
