### ISSUE TITLE
Multiple Remote Signs

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Movecraft#81]
With the update of multiple remote signs allowed to be triggered at once, you can abuse it to click signs that shouldn't be able to be clicked.

Examples include, but are not limited to:
- Being able to teleport onto a Mounted Gun sign (from https://github.com/APDevTeam/Ap-Turrets) from anywhere on a craft
- Being able to click deadbolt signs, and edit them remotely
- And many more

EDIT:  I propose to fix this we disable clicking of blank remote signs (as they will trigger every sign on a craft) and add a blacklist of signs to the config (so servers can disable Mounted Guns or Deadbolt remotes as they wish).

**Comment by FrozenBeard** [comment]
What's this AP Turrets? Sounds interesting.

**Comment by TylerS1066** [comment]
> What's this AP Turrets? Sounds interesting.

It adds "Mounted Gun" signs that allow a player to right click the sign and change into a sort of turret mode, where they can then right click with a button and fire arrows.  It is very effective at balancing ships vs god armored players (as it can 2-3 shot them if configured correctly).

**Comment by FrozenBeard** [comment]
haha that sounds awesome! Is there a build somewhere to have a play with?
