### ISSUE TITLE
Configurable collision sounds.

### ISSUE THREAD

**Issue by wolfebersahd** [APDevTeam/Movecraft#87]
**Is your feature request related to a problem? Please describe.**
I have had complaints on the 2 servers I run, that people don't enjoy the "clang" sounds of anvils when flying a fast ships and colliding with an obstacle. The anvil sound is spammed until you release right click or turn off cruise. Cruise in particular can be debilitating when colliding with and obstacle in a fast ship and having to rush to the cruise sign to turn it off. A fast ship is above 10 speed, which means the anvil sounds plays every two in-game tick, or 10 times a second.

**Describe the solution you'd like**
1. Being able to limit the collision sound once per 2 seconds (configurable time) to avoid noise spam.

Personally I actually like the "clang" anvil sound, but my players have asked the following, but it's not really all that pressing.
1. Being able to configure the collision sound via the general configs globally, or per craft type.
2. Having a different collision sound depending on what block you collide with.

**Comment by cccm5** [comment]
I could probably just make ships stop cruising on collision as an option in the craft type if that works? It's required for crafts to keep cruising in certain cases such as torpedoes, but it can certainly be turned off when unecisarry.

**Comment by wolfebersahd** [comment]
That actually sounds like a great fix. But the issue is if they're stick piloting or using WASD to pilot, they can still get the anvil noise spam. It's not as debilitating as the cruise issue, but still bothersome to hear the clang several times before you let go of right click or the directional button. Especially when trying to navigate tight inlets or narrow spaces.

**Comment by wolfebersahd** [comment]
Hello,

Just curious if there has been any progress on this?

Thanks,

**Comment by cccm5** [comment]
You can now configure collision sounds via setting the `collisionSound` option in a craft file
