### ISSUE TITLE
Moving a water based ship will fill it with water if its below sea-level.

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#94]
Paper version git-Paper-1595 (MC: 1.12.2)
Movecraft: 7.0.0_pre-release_6
FAWE/WE: FastAsyncWorldEdit version 19.01.01-56a71fa-1244-22.0.6 (Using the WE that comes with FAWE for best compatibility)

Sea based ships that have air as part of the ship design that goes below the sea level will be filled with water once moved. 
See this gif for a simple demonstration https://imgur.com/a/idxRkM8
It is also demonstrating the bug #93

**Comment by FrozenBeard** [comment]
Bump

**Comment by TDLF8** [comment]
I see this problem too
